{
 "title": "RabbitMQ 指标(kbudde/rabbitmq_exporter)",
 "description": "Basic rabbitmq host stats: Node Stats, Exchanges, Channels, Consumers,  Connections, Queues, Messages, Messages per Queue, Memory, File Descriptors, Sockets.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster_id",
    "label": "集群",
    "query": "SELECT DISTINCT scope_id AS __value, \nCASE \n  WHEN c.name != '' THEN c.name\n  ELSE scope_id\nEND AS __text\nFROM data_scope \nLEFT JOIN clusters c ON scope_id  = c.id\nWHERE type = 'cluster'"
   },
   {
    "name": "instance",
    "query": "label_values(rabbitmq_up{cluster_id=~\"$cluster_id\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "RabbitMQ Server",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_up{instance=~\"$instance.*\", cluster_id=~\"$cluster_id\"}"
    }
   ]
  },
  {
   "title": "Node up Stats",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rabbitmq_running{instance=~\"$instance.*\", cluster_id=~\"$cluster_id\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Exchanges",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rabbitmq_exchangesTotal{instance=~\"$instance.*\", cluster_id=~\"$cluster_id\"}",
     "legendFormat": "{{instance}}:exchanges"
    }
   ]
  },
  {
   "title": "Channels",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rabbitmq_channelsTotal{instance=~\"$instance.*\", cluster_id=~\"$cluster_id\"}",
     "legendFormat": "{{instance}}:channels"
    }
   ]
  },
  {
   "title": "Consumers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rabbitmq_consumersTotal{instance=~\"$instance.*\", cluster_id=~\"$cluster_id\"}",
     "legendFormat": "{{instance}}:consumers"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rabbitmq_connectionsTotal{instance=~\"$instance.*\", cluster_id=~\"$cluster_id\"}",
     "legendFormat": "{{instance}}:connections"
    }
   ]
  },
  {
   "title": "Queues",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rabbitmq_queuesTotal{instance=~\"$instance.*\", cluster_id=~\"$cluster_id\"}",
     "legendFormat": "{{instance}}:queues"
    }
   ]
  },
  {
   "title": "Messages/host",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (vhost)(rabbitmq_queue_messages_ready{instance=~\"$instance.*\", cluster_id=~\"$cluster_id\"})",
     "legendFormat": "{{vhost}}:ready"
    },
    {
     "expr": "sum by (vhost)(rabbitmq_queue_messages_published_total{instance=~\"$instance.*\", cluster_id=~\"$cluster_id\"})",
     "legendFormat": "{{vhost}}:published"
    },
    {
     "expr": "sum by (vhost)(rabbitmq_queue_messages_delivered_total{instance=~\"$instance.*\", cluster_id=~\"$cluster_id\"})",
     "legendFormat": "{{vhost}}:delivered"
    },
    {
     "expr": "sum by (vhost)(rabbitmq_queue_messages_unacknowledged{instance=~\"$instance.*\", cluster_id=~\"$cluster_id\"})",
     "legendFormat": "{{vhost}}:unack"
    }
   ]
  },
  {
   "title": "Messages / Queue",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{instance=~\"$instance.*\", cluster_id=~\"$cluster_id\"}",
     "legendFormat": "{{queue}}:{{durable}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rabbitmq_node_mem_used{instance=~\"$instance.*\", cluster_id=~\"$cluster_id\"}",
     "legendFormat": "{{node}}:used"
    },
    {
     "expr": "rabbitmq_node_mem_limit{instance=~\"$instance.*\", cluster_id=~\"$cluster_id\"}",
     "legendFormat": "{{node}}:limit"
    }
   ]
  },
  {
   "title": "FIle descriptors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rabbitmq_fd_used{instance=~\"$instance.*\", cluster_id=~\"$cluster_id\"}",
     "legendFormat": "{{node}}:used"
    },
    {
     "expr": "rabbitmq_fd_total{instance=~\"$instance.*\", cluster_id=~\"$cluster_id\"}",
     "legendFormat": "{{node}}:total"
    }
   ]
  },
  {
   "title": "Sockets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rabbitmq_sockets_used{instance=~\"$instance.*\", cluster_id=~\"$cluster_id\"}",
     "legendFormat": "{{node}}:used"
    },
    {
     "expr": "rabbitmq_sockets_total{instance=~\"$instance.*\", cluster_id=~\"$cluster_id\"}",
     "legendFormat": "{{node}}:total"
    }
   ]
  }
 ]
}