{
 "title": "MySQL 指标",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "job", "query": "label_values(mysql_up, job)" },
   {
    "name": "instance",
    "query": "label_values(mysql_up, instance)"
   }
  ]
 },
 "panels": [
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "运行时间",
   "type": "stat",
   "description": "**运行时间**\n\nMySQL 服务启动运行的时间",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_status_uptime{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "每秒查询数",
   "type": "stat",
   "description": "**每秒查询数**\n\n根据 MySQL 的“SHOW STATUS”命令报告的查询MySQL在最后一秒内执行的语句数。",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "rate(mysql_global_status_queries{job=~\"$job\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "InnoDB 缓冲池",
   "type": "stat",
   "description": "**InnoDB 缓存池大小**\nInnoDB 维护一个称为缓冲池的存储区域，用于在内存中缓存数据和索引。了解 InnoDB 缓冲池的工作原理，并利用它将经常访问的数据保存在内存中，是 MySQL 调优的最重要方面之一。目标是将工作集保存在内存中。在大多数情况下，这应该是专用数据库主机上可用内存的 60%-90%，但取决于许多因素。",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_variables_innodb_buffer_pool_size{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "连接",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "MySQL 连接数",
   "type": "graph",
   "description": "**最大连接数** \n\nMax Connections 是允许同时连接的最大客户端数量。增加此值会增加 mysqld 所需的文件描述符数量。如果所需的描述符数量不可用，服务器会降低 Max Connections 的值。\n\nmysqld 实际上允许 Max Connections + 1 个客户端进行连接。额外的连接保留给具有 SUPER 权限的帐户使用，例如 root。\n\nMax Used Connections 是自服务器启动以来同时使用的最大连接数。\n\nConnections 是尝试连接 MySQL 服务器的次数（无论成功与否）。",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(max_over_time(mysql_global_status_threads_connected{job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Connections"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(mysql_global_status_max_used_connections{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "Max Used Connections"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(mysql_global_variables_max_connections{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "Max Connections"
    }
   ]
  },
  {
   "title": "MySQL 客户端线程活跃数",
   "type": "graph",
   "description": "**MySQL 活跃线程数**\n\n已连接线程数是打开的连接数，而运行线程数是未休眠的线程数。",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Threads" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(max_over_time(mysql_global_status_threads_connected{job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Peak Threads Connected"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(max_over_time(mysql_global_status_threads_running{job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Peak Threads Running"
    },
    {
     "expr": "sum(avg_over_time(mysql_global_status_threads_running{job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Avg Threads Running"
    }
   ]
  },
  {
   "title": "表锁定统计",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "MySQL 请求数",
   "type": "graph",
   "description": "**MySQL 请求数**\n\n服务器执行的语句数。这仅包括客户端发送到服务器的语句，而不包括存储程序内执行的语句，这与 QPS 计算中使用的查询不同。\n\n此变量不计算以下命令：\n* ``COM_PING``\n* ``COM_STATISTICS``\n* ``COM_STMT_PREPARE``\n* ``COM_STMT_CLOSE``\n* ``COM_STMT_RESET``",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_questions{job=~\"$job\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MySQL 线程缓存",
   "type": "graph",
   "description": "**MySQL 线程缓存**\n\nthread_cache_size 变量设置服务器应缓存多少个线程以供重用。当客户端断开连接时，如果缓存未满，则客户端的线程将放入缓存中。它在 MySQL 5.6.8 及更高版本中自动调整大小（上限为 100）。如果可能，通过重用从缓存中获取的线程来满足线程请求，并且只有当缓存为空时才会创建新线程。\n\n* *Threads_created*：为处理连接而创建的线程数。\n* *Threads_cached*：线程缓存中的线程数。",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(mysql_global_variables_thread_cache_size{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "Thread Cache Size"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(mysql_global_status_threads_cached{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "Threads Cached"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mysql_global_status_threads_created{job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Threads Created"
    }
   ]
  },
  {
   "title": "临时对象统计",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "MySQL 临时对象数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mysql_global_status_created_tmp_tables{job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Created Tmp Tables"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mysql_global_status_created_tmp_disk_tables{job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Created Tmp Disk Tables"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mysql_global_status_created_tmp_files{job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Created Tmp Files"
    }
   ]
  },
  {
   "title": "MySQL 查询类型",
   "type": "graph",
   "description": "**MySQL 查询类型**\n\n与大多数关系数据库一样，基于索引进行选择比扫描整个表的数据更有效。\n\n* ***Select Scan*** 表示有多少查询导致全表扫描，其中必须读取表中的所有数据并丢弃或返回。\n* ***Select Range*** 表示有多少查询使用了范围扫描，这意味着 MySQL 扫描了给定范围内的所有行。\n* ***Select Full Join*** 表示未在索引上连接的连接数，这通常会对性能造成巨大影响。",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mysql_global_status_select_full_join{job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Select Full Join"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mysql_global_status_select_full_range_join{job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Select Full Range Join"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mysql_global_status_select_range{job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Select Range"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mysql_global_status_select_range_check{job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Select Range Check"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mysql_global_status_select_scan{job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Select Scan"
    }
   ]
  },
  {
   "title": "排序",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "MySQL 排序数",
   "type": "graph",
   "description": "**MySQL Sorts**\n\n由于查询的结构、顺序或其他要求，MySQL 会在返回行之前对行进行排序。例如，如果某个表的排序顺序为 1 到 10，但您希望将结果反转，则 MySQL 必须对行进行排序以返回 10 到 1 的顺序。\n\n此图还显示了何时排序必须扫描整个表或给定范围的表才能返回结果，以及哪些无法通过索引进行排序。",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mysql_global_status_sort_rows{job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Sort Rows"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mysql_global_status_sort_range{job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Sort Range"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mysql_global_status_sort_merge_passes{job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Sort Merge Passes"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mysql_global_status_sort_scan{job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Sort Scan"
    }
   ]
  },
  {
   "title": "MySQL 慢查询",
   "type": "graph",
   "description": "**MySQL Slow Queries**\n\n慢查询是指比 long_query_time 设置更慢的查询。例如，如果您将 long_query_time 设置为 3，则所有需要超过 3 秒才能完成的查询都会显示在这张图上。",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mysql_global_status_slow_queries{job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Slow Queries"
    }
   ]
  },
  {
   "title": "中断",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "MySQL 中断连接数",
   "type": "graph",
   "description": "**中断连接数**\n\n当给定主机连接到 MySQL 并且连接在中途中断（例如由于凭据错误）时，MySQL 会将该信息保存在系统表中（自 5.6 起，此表在 performance_schema 中公开）。\n\n如果没有成功连接的失败请求数量达到 max_connect_errors 的值，mysqld 会假定出现问题并阻止主机进一步连接。\n\n要再次允许来自该主机的连接，您需要发出“FLUSH HOSTS”语句。",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mysql_global_status_aborted_connects{job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Aborted Connects (attempts)"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mysql_global_status_aborted_clients{job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Aborted Clients (timeout)"
    }
   ]
  },
  {
   "title": "MySQL 表锁定",
   "type": "graph",
   "description": "**Table Locks**\n\nMySQL 出于各种原因采用多种不同的锁定。在此图中，我们可以看到 MySQL 从存储引擎请求了多少个表级锁定。在 InnoDB 的情况下，很多时候锁定实际上可能是行锁定，因为它只在少数特定情况下采用表级锁定。\n\n比较立即锁定和等待锁定是最有用的。如果等待锁定在上升，则意味着存在锁定争用。否则，立即锁定的上升和下降是正常活动。",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mysql_global_status_table_locks_immediate{job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Table Locks Immediate"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mysql_global_status_table_locks_waited{job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Table Locks Waited"
    }
   ]
  },
  {
   "title": "网络状态",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {}
   ]
  },
  {
   "title": "MySQL 网络流量",
   "type": "graph",
   "description": "**MySQL Network Traffic**\n\n这里我们可以看到 MySQL 产生了多少网络流量。outbound是 MySQL 发出的网络流量，inbound是 MySQL 收到的网络流量。",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mysql_global_status_bytes_received{job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Inbound"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mysql_global_status_bytes_sent{job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "内存使用",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {}
   ]
  },
  {
   "title": "MySQL 内存使用总览",
   "type": "graph",
   "description": "***System Memory***: 系统的总内存。\\\n***InnoDB Buffer Pool Data***: InnoDB 维护一个称为缓冲池的存储区域，用于在内存中缓存数据和索引。\\\n***TokuDB Cache Size***: 功能与 InnoDB 缓冲池类似，TokuDB 将为其自己的缓存分配 50% 的已安装 RAM。\\\n***Key Buffer Size***: MYISAM 表的索引块被缓冲并由所有线程共享。key_buffer_size 是用于索引块的缓冲区的大小。\\\n***Adaptive Hash Index Size***: 当 InnoDB 注意到某些索引值被非常频繁地访问时，它会在 B-Tree 索引之上的内存中为它们构建一个哈希索引。\\\n ***Query Cache Size***: 查询缓存将 SELECT 语句的文本与发送给客户端的相应结果一起存储。查询缓存存在巨大的可扩展性问题，因为同一时间只有一个线程可以在查询缓存中执行操作。\\\n***InnoDB Dictionary Size***:数据字典是 InnoDB 的内部表目录。InnoDB 将数据字典存储在磁盘上，并在服务器运行时将条目加载到内存中。\\\n***InnoDB Log Buffer Size***: MySQL InnoDB 日志缓冲区允许事务运行，而无需在事务提交之前将日志写入磁盘。",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(mysql_global_status_innodb_page_size{job=~\"$job\", instance=~\"$instance\"} * on (instance) mysql_global_status_buffer_pool_pages{job=~\"$job\", instance=~\"$instance\", state=\"data\"})",
     "legendFormat": "InnoDB Buffer Pool Data"
    },
    {
     "expr": "sum(mysql_global_variables_innodb_log_buffer_size{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "InnoDB Log Buffer Size"
    },
    {
     "expr": "sum(mysql_global_variables_innodb_additional_mem_pool_size{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "InnoDB Additional Memory Pool Size"
    },
    {
     "expr": "sum(mysql_global_status_innodb_mem_dictionary{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "InnoDB Dictionary Size"
    },
    {
     "expr": "sum(mysql_global_variables_key_buffer_size{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "Key Buffer Size"
    },
    {
     "expr": "sum(mysql_global_variables_query_cache_size{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "Query Cache Size"
    },
    {
     "expr": "sum(mysql_global_status_innodb_mem_adaptive_hash{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "Adaptive Hash Index Size"
    },
    {
     "expr": "sum(mysql_global_variables_tokudb_cache_size{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "TokuDB Cache Size"
    }
   ]
  },
  {
   "title": "命令，处理，进程",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {}
   ]
  },
  {
   "title": "命令数统计",
   "type": "graph",
   "description": "**Top Command Counters**\n\nCom_{{xxx}} 语句计数器变量表示每个 xxx 语句的执行次数。每种类型的语句都有一个状态变量。例如，Com_delete 和 Com_update 分别计数 [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) 和 [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) 语句。Com_delete_multi 和 Com_update_multi 类似，但适用于使用多表语法的 [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) 和 [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) 语句。",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "topk(5, rate(mysql_global_status_commands_total{job=~\"$job\", instance=~\"$instance\"}[$__interval])>0)",
     "legendFormat": "Com_{{ command }}"
    }
   ]
  },
  {
   "title": "MySQL 处理统计",
   "type": "graph",
   "description": "**MySQL Handlers**\n\n处理程序统计信息是有关 MySQL 如何选择、更新、插入和修改行、表和索引的内部统计信息。\n\n这实际上是存储引擎和 MySQL 之间的层。\n\n* 当服务器执行全表扫描时，`read_rnd_next` 会递增，您肯定不希望看到此计数器的值过高。\n* 当使用索引完成读取时，`read_key` 会递增。\n* 当要求存储引擎“读取下一个索引条目”时，`read_next` 会递增。值过高意味着执行了大量索引扫描。",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_handlers_total{instance=~\"$host\", handler!~\"commit|rollback|savepoint.*|prepare\"}[$__interval]) or irate(mysql_global_status_handlers_total{instance=~\"$host\", handler!~\"commit|rollback|savepoint.*|prepare\"}[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "MySQL 事务处理",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_handlers_total{instance=~\"$host\", handler=~\"commit|rollback|savepoint.*|prepare\"}[$__interval]) or irate(mysql_global_status_handlers_total{instance=~\"$host\", handler=~\"commit|rollback|savepoint.*|prepare\"}[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "进程状态",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_info_schema_threads{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "每小时进程状态",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "topk(5, avg_over_time(mysql_info_schema_threads{job=~\"$job\", instance=~\"$instance\"}[1h]))",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "查询缓存",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 },
   "targets": [
    {}
   ]
  },
  {
   "title": "MySQL 查询缓存大小",
   "type": "graph",
   "description": "**MySQL Query Cache Memory**\n\n查询缓存存在巨大的可扩展性问题，因为只有一个线程可以同时在查询缓存中执行操作。这种序列化不仅适用于 SELECT，也适用于 INSERT/UPDATE/DELETE。\n\n这也意味着 `query_cache_size` 设置的越大，这些操作就越慢。在并发环境中，MySQL 查询缓存很快就会成为争用点，从而降低性能。MariaDB 和 AWS Aurora 已努力尝试消除其 MySQL 版本中的查询缓存争用，而 MySQL 8.0 已取消查询缓存功能。\n\n大多数环境的推荐设置是设置：\n``query_cache_type=0``\n``query_cache_size=0``\n\n请注意，虽然您可以动态更改这些值，但要完全消除争用点，您必须重新启动数据库。",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_qcache_free_memory{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Free Memory"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_query_cache_size{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Query Cache Size"
    }
   ]
  },
  {
   "title": "MySQL 查询缓存活跃情况",
   "type": "graph",
   "description": "**MySQL Query Cache Activity**\n\n查询缓存存在巨大的可扩展性问题，因为只有一个线程可以同时在查询缓存中执行操作。这种序列化不仅适用于 SELECT，也适用于 INSERT/UPDATE/DELETE。\n\n这也意味着 `query_cache_size` 设置的越大，这些操作就越慢。在并发环境中，MySQL 查询缓存很快就会成为争用点，从而降低性能。MariaDB 和 AWS Aurora 已努力尝试消除其 MySQL 版本中的查询缓存争用，而 MySQL 8.0 已取消查询缓存功能。\n\n大多数环境的推荐设置是设置：\n``query_cache_type=0``\n``query_cache_size=0``\n\n请注意，虽然您可以动态更改这些值，但要完全消除争用点，您必须重新启动数据库。",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_qcache_hits{job=~\"$job\", instance=~\"$instance\"}[$__interval]) or irate(mysql_global_status_qcache_hits{job=~\"$job\", instance=~\"$instance\"}[5m])",
     "legendFormat": "Hits"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_qcache_inserts{job=~\"$job\", instance=~\"$instance\"}[$__interval]) or irate(mysql_global_status_qcache_inserts{job=~\"$job\", instance=~\"$instance\"}[5m])",
     "legendFormat": "Inserts"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_qcache_not_cached{job=~\"$job\", instance=~\"$instance\"}[$__interval]) or irate(mysql_global_status_qcache_not_cached{job=~\"$job\", instance=~\"$instance\"}[5m])",
     "legendFormat": "Not Cached"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_qcache_lowmem_prunes{job=~\"$job\", instance=~\"$instance\"}[$__interval]) or irate(mysql_global_status_qcache_lowmem_prunes{job=~\"$job\", instance=~\"$instance\"}[5m])",
     "legendFormat": "Prunes"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_qcache_queries_in_cache{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Queries in Cache"
    }
   ]
  },
  {
   "title": "文件数量",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 },
   "targets": [
    {}
   ]
  },
  {
   "title": "MySQL 当前文件打开数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_opened_files{job=~\"$job\", instance=~\"$instance\"}[$__interval]) or irate(mysql_global_status_opened_files{job=~\"$job\", instance=~\"$instance\"}[5m])",
     "legendFormat": "Openings"
    }
   ]
  },
  {
   "title": "MySQL 文件打开统计",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_open_files{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Open Files"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_open_files_limit{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Open Files Limit"
    },
    {
     "expr": "mysql_global_status_innodb_num_open_files{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "InnoDB Open Files"
    }
   ]
  },
  {
   "title": "打开的表",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 },
   "targets": [
    {}
   ]
  },
  {
   "title": "MySQL 表状态",
   "type": "graph",
   "description": "**MySQL Table Open Cache Status**\n\n建议将 `table_open_cache_instances` 设置为与虚拟 CPU 松散关联，请记住，实例越多意味着缓存被拆分的次数越多。如果您将缓存设置为 500，但有 10 个实例，则每个缓存将只缓存 50 个。\n\n`table_definition_cache` 和 `table_open_cache` 可以保留为默认值，因为它们是自动调整大小的 MySQL 5.6 及更高版本（即：不要将它们设置为任何值）。",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_opened_tables{job=~\"$job\", instance=~\"$instance\"}[$__interval]) or irate(mysql_global_status_opened_tables{job=~\"$job\", instance=~\"$instance\"}[5m])",
     "legendFormat": "Openings"
    },
    {
     "expr": "rate(mysql_global_status_table_open_cache_hits{job=~\"$job\", instance=~\"$instance\"}[$__interval]) or irate(mysql_global_status_table_open_cache_hits{job=~\"$job\", instance=~\"$instance\"}[5m])",
     "legendFormat": "Hits"
    },
    {
     "expr": "rate(mysql_global_status_table_open_cache_misses{job=~\"$job\", instance=~\"$instance\"}[$__interval]) or irate(mysql_global_status_table_open_cache_misses{job=~\"$job\", instance=~\"$instance\"}[5m])",
     "legendFormat": "Misses"
    },
    {
     "expr": "rate(mysql_global_status_table_open_cache_overflows{job=~\"$job\", instance=~\"$instance\"}[$__interval]) or irate(mysql_global_status_table_open_cache_overflows{job=~\"$job\", instance=~\"$instance\"}[5m])",
     "legendFormat": "Misses due to Overflows"
    },
    {
     "expr": "(rate(mysql_global_status_table_open_cache_hits{job=~\"$job\", instance=~\"$instance\"}[$__interval]) or irate(mysql_global_status_table_open_cache_hits{job=~\"$job\", instance=~\"$instance\"}[5m]))/((rate(mysql_global_status_table_open_cache_hits{job=~\"$job\", instance=~\"$instance\"}[$__interval]) or irate(mysql_global_status_table_open_cache_hits{job=~\"$job\", instance=~\"$instance\"}[5m]))+(rate(mysql_global_status_table_open_cache_misses{job=~\"$job\", instance=~\"$instance\"}[$__interval]) or irate(mysql_global_status_table_open_cache_misses{job=~\"$job\", instance=~\"$instance\"}[5m])))",
     "legendFormat": "Table Open Cache Hit Ratio"
    }
   ]
  },
  {
   "title": "MySQL 打开的表",
   "type": "graph",
   "description": "**MySQL Open Tables**\n\n建议将 `table_open_cache_instances` 设置为与虚拟 CPU 松散关联，请记住，实例越多意味着缓存被拆分的次数越多。如果您将缓存设置为 500，但有 10 个实例，则每个缓存将只缓存 50 个。\n\n`table_definition_cache` 和 `table_open_cache` 可以保留为默认值，因为它们是自动调整大小的 MySQL 5.6 及更高版本（即：不要将它们设置为任何值）。",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 113 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_open_tables{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Open Tables"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_table_open_cache{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Table Open Cache"
    }
   ]
  },
  {
   "title": "MySQL 表定义",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 },
   "targets": [
    {}
   ]
  },
  {
   "title": "MySQL 表定义缓存",
   "type": "graph",
   "description": "**MySQL Table Definition Cache**\n\n建议将 `table_open_cache_instances` 设置为与虚拟 CPU 松散关联，请记住，实例越多意味着缓存被拆分的次数越多。如果您将缓存设置为 500，但有 10 个实例，则每个缓存将只缓存 50 个。\n\n`table_definition_cache` 和 `table_open_cache` 可以保留为默认值，因为它们是自动调整大小的 MySQL 5.6 及更高版本（即：不要将它们设置为任何值）。",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 121 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_open_table_definitions{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Open Table Definitions"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_table_definition_cache{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Table Definitions Cache Size"
    },
    {
     "expr": "rate(mysql_global_status_opened_table_definitions{job=~\"$job\", instance=~\"$instance\"}[$__interval]) or irate(mysql_global_status_opened_table_definitions{job=~\"$job\", instance=~\"$instance\"}[5m])",
     "legendFormat": "Opened Table Definitions"
    }
   ]
  }
 ]
}