{
 "title": "Redis 指标",
 "tags": [
  "ConsulManager",
  "Redis",
  "redis_exporter",
  "StarsL.cn",
  "Prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "vendor", "label": "云厂商", "query": { "query": "label_values(redis_up, vendor)" } },
   {
    "name": "account",
    "label": "账号",
    "query": {
     "query": "label_values(redis_up{vendor=~\"$vendor\"}, account)"
    }
   },
   {
    "name": "group",
    "label": "属组",
    "query": {
     "query": "label_values(redis_up{vendor=~\"$vendor\",account=~\"$account\"}, group)"
    }
   },
   {
    "name": "name",
    "label": "名称",
    "query": {
     "query": "label_values(redis_up{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\"}, name)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(redis_up{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\"}, instance)"
    }
   },
   {
    "name": "iid",
    "query": {
     "query": "label_values(redis_up{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\"}, iid)"
    }
   }
  ]
 },
 "panels": [
  { "title": "总览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "REDIS资源总览表【$vendor：$account：$group】",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_up{account=~\"$account\",group=~\"$group\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(redis_connected_clients{account=~\"$account\",group=~\"$group\"})by(instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(irate(redis_commands_total{account=~\"$account\",group=~\"$group\"} [2m]))by(instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "redis_uptime_in_seconds{account=~\"$account\",group=~\"$group\"} - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(irate(redis_keyspace_hits_total{account=~\"$account\",group=~\"$group\"}[2m]) / (irate(redis_keyspace_misses_total{account=~\"$account\",group=~\"$group\"}[1m]) + irate(redis_keyspace_hits_total{account=~\"$account\",group=~\"$group\"}[2m]))) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (redis_db_keys{account=~\"$account\",group=~\"$group\"}) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(irate(redis_net_input_bytes_total{account=~\"$account\",group=~\"$group\"}[2m])) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(irate(redis_net_output_bytes_total{account=~\"$account\",group=~\"$group\"}[2m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "明细【名称：$name】【实例ID：$iid】", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "redis_uptime_in_seconds{instance=~\"$instance\"}",
     "legendFormat": "Uptime",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(redis_connected_clients{instance=~\"$instance\"})",
     "legendFormat": "客户端连接",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(irate(redis_commands_total{instance=~\"$instance\"} [2m]))",
     "legendFormat": "每秒操作数",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "内存使用量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 2, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_memory_used_bytes{instance=~\"$instance\"}",
     "legendFormat": "used"
    },
    {
     "expr": "redis_memory_max_bytes{instance=~\"$instance\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "每秒网络流量",
   "type": "graph",
   "description": "Network I/O",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 10 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(redis_net_input_bytes_total{instance=~\"$instance\"}[2m]))",
     "legendFormat": "流入"
    },
    {
     "expr": "sum(irate(redis_net_output_bytes_total{instance=~\"$instance\"}[2m]))",
     "legendFormat": "流出"
    }
   ]
  },
  {
   "title": "每秒命中和未命中数量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total{instance=~\"$instance\"}[2m])",
     "legendFormat": "命中数"
    },
    {
     "expr": "irate(redis_keyspace_misses_total{instance=~\"$instance\"}[2m])",
     "legendFormat": "未命中数"
    }
   ]
  },
  {
   "title": "每秒操作数",
   "type": "graph",
   "description": "Total Commands / sec",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(redis_commands_total{instance=~\"$instance\"} [2m])) by (cmd) >1",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "命中率",
   "type": "graph",
   "description": "Hit rate shows the percentage of key space lookups that hit a key.",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(irate(redis_keyspace_hits_total{instance=~\"$instance\"}[2m]) / (irate(redis_keyspace_misses_total{instance=~\"$instance\"}[1m]) + irate(redis_keyspace_hits_total{instance=~\"$instance\"}[2m]))) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "连接与拒绝的客户端",
   "type": "graph",
   "description": "Connected/Blocked Clients",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(redis_connected_clients{instance=~\"$instance\"})",
     "legendFormat": "connected"
    },
    {
     "expr": "sum(redis_blocked_clients{instance=~\"$instance\"})",
     "legendFormat": "blocked"
    }
   ]
  },
  {
   "title": "命令执行平均耗时",
   "type": "graph",
   "description": "Average Time Spent by Command / sec",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(redis_commands_duration_seconds_total{instance =~ \"$instance\"}[2m])) by (cmd)\n  /\nsum(irate(redis_commands_total{instance =~ \"$instance\"}[2m])) by (cmd)\n",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "每秒命令花费的总时长",
   "type": "graph",
   "description": "Total Time Spent by Command / sec",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(redis_commands_duration_seconds_total{instance=~\"$instance\"}[2m])) by (cmd) != 0",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "实例从属连接",
   "type": "graph",
   "description": "This metric will only be non-zero if the instance is a master",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(redis_connected_slaves{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "过期与未过期的Keys",
   "type": "graph",
   "description": "Expiring vs Not-Expiring Keys",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{instance=~\"$instance\"}) by (instance) - sum (redis_db_keys_expiring{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "not expiring"
    },
    {
     "expr": "sum (redis_db_keys_expiring{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "expiring"
    }
   ]
  },
  {
   "title": "过期与驱逐的Keys",
   "type": "graph",
   "description": "Expired/Evicted Keys",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(redis_expired_keys_total{instance=~\"$instance\"}[2m])) by (instance)",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{instance=~\"$instance\"}[5m])) by (instance)",
     "legendFormat": "evicted"
    }
   ]
  },
  {
   "title": "每秒键值对删除次数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(redis_evicted_keys_total{instance=~\"$instance\"}[2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "各DB KEY分布",
   "type": "graph",
   "description": "Total Items per DB",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{instance=~\"$instance\"}) by (db, instance)",
     "legendFormat": "{{ db }}"
    }
   ]
  }
 ]
}