{
 "title": "NGINX Requeset Log DashBoard StarsL.cn",
 "description": "NGINX request log analysis dashboard based on ClickHouse + Vector. Including request and time analysis, abnormal request analysis, user analysis, geographic location distribution map, specified interface analysis, and request log details. https://grafana.com/orgs/starsliao/dashboards",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "project",
    "query": "select concat(database, '.', name)\nfrom system.tables\nwhere database = 'apo' and name like 'logs_%'"
   },
   {
    "name": "server_ip",
    "label": "NGINX",
    "query": "SELECT\nconcat(server_ip ,'#server_ip = \\'',server_ip,'\\'') \nfrom $project PREWHERE $__timeFilter(timestamp) \ngroup by server_ip"
   },
   {
    "name": "domain",
    "label": "domain",
    "query": "select\nconcat(domain,'#domain = \\'',domain,'\\'') \nFROM ${project}\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip}\n\tgroup by domain \n\torder by count() desc\n"
   },
   {
    "name": "status",
    "label": "status",
    "query": "all : 1=1, 1XX : status >=100 and status <200, 200 : status = 200, 2XX : status >=200 and status <300, 3XX : status >=300 and status <400, 4XX : status >=400 and status <500, 5XX : status >=500 and status <600"
   },
   {
    "name": "uri",
    "label": "url",
    "query": "select path FROM ${project}\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain}  and ${status}\n\tgroup by path\n\torder by count() desc\nlimit 100\n"
   },
   {
    "name": "cip",
    "label": "Specified user IP analysis",
    "query": "select client_ip FROM ${project}\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain}  and ${status}\n\tgroup by client_ip\n\torder by count() desc\nlimit 100\n"
   },
   {
    "name": "cal_interval",
    "label": "interval",
    "query": "1s : 1, 10s : 10, 15s : 15, 30s : 30, 1m : 60,5m : 300, 10m : 600, 30m : 1800, 1h : 3600 "
   }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average response time of each domain name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,avg(responsetime) as \"平均\",domain\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip}\r\nGROUP BY time,domain\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Overall QPS of each domain name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "\tSELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time, count() / ${cal_interval} AS avgqps, domain\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip}\r\n\tGROUP BY time,domain\r\n  order by time"
    }
   ]
  },
  {
   "title": "PV ratio of each domain name",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\tSELECT\r\n    domain,\r\n    COUNT()\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip}\r\n\tGROUP BY domain\r\n  order by COUNT() DESC"
    }
   ]
  },
  {
   "title": "The proportion of UV requests by domain name",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\tSELECT\r\n    domain,\r\n    COUNT(DISTINCT client_ip)\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and  ${server_ip}\r\n\tGROUP BY domain\r\n  order by COUNT() DESC"
    }
   ]
  },
  {
   "title": "Request and time analysis【$domain】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time, sum(request_length) * 8 / ${cal_interval} as \"Maximum request amount\"\r\nFROM ${project}\r\nPREWHERE toDate(timestamp) = today() and ${server_ip} and ${domain}\r\nGROUP BY time\r\n"
    },
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time, sum(response_length) * 8 / ${cal_interval} as \"Maximum return amount\"\r\n\tFROM ${project}\r\n\tPREWHERE toDate(timestamp) = today() and ${server_ip} and ${domain}\r\nGROUP BY time\r\n"
    },
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time, count() / ${cal_interval} AS \"Maximun QPS\"\r\n\tFROM ${project}\r\n\tPREWHERE toDate(timestamp) = today() and ${server_ip} and ${domain}\r\n\tGROUP BY time\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,countIf(status<400)/count() *100 as \"Request success rate\"\r\nFROM ${project} \r\nPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain}\r\ngroup by time\r\norder by time\r\n"
    },
    {
     "rawSql": "\tSELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time, count()/${cal_interval} AS \"Current QPS\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain}\r\n\tGROUP BY time\r\n  order by time"
    },
    {
     "rawSql": "\tSELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,avg(responsetime) as \"Overall response time\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain}\r\nGROUP BY time\r\nORDER BY time"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT count()/10000 as \"Total PV (million)\"\r\nFROM ${project}\r\n\tPREWHERE toDate(timestamp) = today() and ${server_ip} and ${domain}"
    },
    {
     "rawSql": "\tSELECT COUNT(DISTINCT client_ip) AS \"Total UV\"\r\n\tFROM ${project}\r\n\tPREWHERE toDate(timestamp) = today() and ${server_ip} and ${domain}\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    CASE\r\n        WHEN status >= 100 AND status < 200 THEN '1XX'     \r\n        WHEN status >= 200 AND status < 300 THEN '2XX'\r\n        WHEN status >= 300 AND status < 400 THEN '3XX'\r\n        WHEN status >= 400 AND status < 500 THEN '4XX'\r\n        WHEN status >= 500 AND status < 600 THEN '5XX'\r\n        ELSE 'Other'\r\n    END AS status_category,\r\n    COUNT(*) AS count\r\nFROM ${project}\r\nPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain}\r\nGROUP BY \r\n    status_category\r\norder BY\r\n    status_category"
    }
   ]
  },
  {
   "title": "HTTP${status} QPS and UV per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "\tSELECT toStartOfInterval(timestamp, INTERVAL 60 SECOND) AS time, COUNT(DISTINCT client_ip) AS \"每分钟UV\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and ${status}\r\n\tGROUP BY time\r\n  order by time"
    },
    {
     "rawSql": "\tSELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time, count() / ${cal_interval} AS \"QPS\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and ${status}\r\n\tGROUP BY time\r\n  order by time"
    }
   ]
  },
  {
   "title": "HTTP${status} response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,\r\n  quantileExact(0.99)(responsetime) as P99\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and ${status}\r\nGROUP BY time\r\nORDER BY time\r\n\r\n\r\n"
    },
    {
     "rawSql": "\r\nSELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,\r\n  quantileExact(0.90)(responsetime) as P90\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and ${status}\r\nGROUP BY time\r\nORDER BY time\r\n\r\n\r\n"
    },
    {
     "rawSql": "\r\nSELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,\r\n  quantileExact(0.50)(responsetime) as P50\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and ${status}\r\nGROUP BY time\r\nORDER BY time\r\n\r\n\r\n"
    },
    {
     "rawSql": "\r\nSELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,\r\n  quantileExact(0.75)(responsetime) as P75\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and ${status}\r\nGROUP BY time\r\nORDER BY time\r\n\r\n\r\n"
    },
    {
     "rawSql": "\r\nSELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,\r\n  quantileExact(0.95)(responsetime) as P95\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and ${status}\r\nGROUP BY time\r\nORDER BY time\r\n\r\n\r\n"
    },
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,avg(responsetime) as \"avg\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and ${status}\r\nGROUP BY time\r\nORDER BY time"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "\tSELECT\r\n\t  `top_path` as TOP_Path, COUNT() AS PV, COUNT(DISTINCT client_ip) as \"UV\",avg(response_length) as \"avg return\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain}\r\n\tGROUP BY `top_path`\r\n  order by COUNT() DESC\r\n"
    },
    {
     "rawSql": "\tSELECT\r\n\t  `top_path` as TOP_Path,avg(responsetime) as \"Specify the status response time\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\n\tGROUP BY `top_path`"
    },
    {
     "rawSql": "SELECT `top_path` as TOP_Path,\r\ncountIf(status >=400 and status < 500) as 4XX,\r\ncountIf(status>=500) as 5XX\r\nFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain}\r\nGROUP BY \r\n    `top_path`"
    }
   ]
  },
  {
   "title": "HTTP${status} QPS ratio of each backend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "HTTP${status} QPS of each backend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "\tSELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time, count() / ${cal_interval} AS avgqps, upstreamhost\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and ${status}\r\n\tGROUP BY time,upstreamhost\r\n  order by time"
    },
    {
     "rawSql": "\tSELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time, count() / ${cal_interval} AS avgqps, 'Total'\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and ${status}\r\n\tGROUP BY time\r\n  order by time"
    }
   ]
  },
  {
   "title": "Average HTTP${status} response time of each backend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,avg(responsetime) as rt,'Total'\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and ${status}\r\nGROUP BY time\r\nORDER BY time"
    },
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,upstreamhost,avg(responsetime) as rt\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and ${status}\r\nGROUP BY time,upstreamhost\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "HTTP${status} time consumption distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,\r\n    CASE\r\n        WHEN responsetime >= 0 AND responsetime <= 0.01 THEN '0-10'\r\n        WHEN responsetime > 0.01 AND responsetime <= 0.025 THEN '0-25'\r\n        WHEN responsetime > 0.025 AND responsetime <= 0.05 THEN '1-50'\r\n        WHEN responsetime > 0.05 AND responsetime <= 0.1 THEN '2-100'\r\n        WHEN responsetime > 0.1 AND responsetime <= 0.15 THEN '3-150'\r\n        WHEN responsetime > 0.15 AND responsetime <= 0.2 THEN '4-200'\r\n        WHEN responsetime > 0.2 AND responsetime <= 0.3 THEN '5-300'\r\n        WHEN responsetime > 0.3 AND responsetime <= 0.5 THEN '6-500'\r\n        WHEN responsetime > 0.5 AND responsetime <= 1 THEN '7-1000'\r\n        ELSE 'N-MAX'\r\n    END AS status_category,\r\n    COUNT() AS count\r\nFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and ${status}\r\nGROUP BY \r\n    time,status_category\r\norder BY\r\n    time,status_category"
    }
   ]
  },
  {
   "title": "HTTP${status} request method ratio",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\tSELECT\r\n\t  request_method, \r\n    COUNT()\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\n\tGROUP BY request_method\r\n  order by COUNT() DESC"
    }
   ]
  },
  {
   "title": "NGINX HTTP${status} QPS ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "NGINX HTTP${status} QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "\tSELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time, server_ip, count() / ${cal_interval} AS avgqps\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and ${status}\r\n\tGROUP BY time,server_ip\r\n  order by time"
    },
    {
     "rawSql": "\tSELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time, count() / ${cal_interval} AS avgqps,'Total'\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and ${status}\r\n\tGROUP BY time\r\n  order by time"
    }
   ]
  },
  {
   "title": "Average response time of each NGINX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,avg(responsetime) as rt, 'Total'\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and ${status}\r\nGROUP BY time\r\nORDER BY time"
    },
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,server_ip,avg(responsetime) as rt\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and ${status}\r\nGROUP BY time,server_ip\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "HTTP${status} hourly PV and UV (last 25 hours)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "\tSELECT toStartOfHour(timestamp) AS time, count() AS \"PV per hour\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and ${status}\r\n\tGROUP BY time\r\n  order by time"
    },
    {
     "rawSql": "\tSELECT toStartOfHour(timestamp) AS time, COUNT(DISTINCT client_ip) AS \"UV per hour\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and ${status}\r\n\tGROUP BY time\r\n  order by time"
    }
   ]
  },
  {
   "title": "HTTP${status} request and response",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time, sum(request_length) * 8 / ${cal_interval} as \"Requests per second\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and ${status}\r\nGROUP BY time\r\nORDER BY time"
    },
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time, sum(response_length) * 8 / ${cal_interval} as \"Returns per second\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and ${status}\r\nGROUP BY time\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Abnormal request analysis [$domain]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 }
  },
  {
   "title": "TOP_Path HTTP abnormal status code (accumulated value per minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  toStartOfMinute(timestamp) as time,\r\n  count() as value,top_path,toString(status) as \"state\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and status >= 500\r\nGROUP BY time,status,top_path\r\nORDER BY time\r\n"
    }
   ]
  },
  {
   "title": "HTTP abnormal status code (same URI accumulated > 10 times per minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  toStartOfMinute(timestamp) as time,\r\n  count() as count,path\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and status >= 500\r\nGROUP BY time,path\r\nhaving count >= 10\r\nORDER BY time\r\n"
    }
   ]
  },
  {
   "title": "Number of non-HTTP200 requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 14, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "\tSELECT toStartOfInterval(timestamp, INTERVAL 60 SECOND) AS time,toString(status), count(status)  AS HTTP\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and status != 200\r\n\tGROUP BY time,status\r\n  order by time"
    }
   ]
  },
  {
   "title": "Number of program requests per 10 minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "\tSELECT toStartOfInterval(timestamp, INTERVAL 10 MINUTE) AS time, COUNT() as \"app\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and (http_user_agent like '%Java%' OR http_user_agent like '%python%')\r\n\tGROUP BY time\r\n  order by time"
    },
    {
     "rawSql": "\tSELECT toStartOfInterval(timestamp, INTERVAL 10 MINUTE) AS time, COUNT() as \"爬虫\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and (http_user_agent like '%spider%' OR http_user_agent like '%bot%')\r\n\tGROUP BY time\r\n  order by time"
    }
   ]
  },
  {
   "title": "TOP_Path The number of requests that take longer than 500ms per minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT toStartOfMinute(timestamp) AS time, top_path\r\n\t, countIf(responsetime > 0.5) AS slow_requests\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain}\r\nGROUP BY time, top_path\r\nHAVING slow_requests > 0\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "TOP_Path requests longer than 500ms, proportion of all requests longer than 500ms",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Average response time for domain name requests",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n\tdomain as \"user_domain\",avg(responsetime) as \"resptime\", count() as PV,COUNT(DISTINCT client_ip) as UV\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain}\r\n\tGROUP BY domain"
    }
   ]
  },
  {
   "title": "TOP30 slowest requests (PV>100)",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "\tSELECT\r\n\t  `path` as \"request_path\", avg(responsetime) as \"avg_resp_time\",COUNT() AS PV, COUNT(DISTINCT client_ip) as \"UV\",avg(response_length) as \"avg_return\"\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain}\r\n\tGROUP BY `path`\r\n\tHAVING PV >100\r\n\torder by \"avg_resp_time\" DESC\r\n\tLIMIT 30;"
    }
   ]
  },
  {
   "title": "P90 NGINX processing time is slowest TOP30 (PV>10)",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "\tSELECT\r\n\t  `path` as \"request_path\",quantileExact(0.90)(duration) as \"P90NGtime\",avg(response_length) as \"avg_return\", avg(responsetime) as \"avg_resp_time\",COUNT() AS PV, COUNT(DISTINCT client_ip) as \"UV\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain}\r\n\tGROUP BY `path`\r\n\tHAVING PV > 10\r\n\torder by \"P90NGtime\" DESC\r\n\tLIMIT 30;"
    }
   ]
  },
  { "title": "URI request analysis [$domain]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "TOP_Path HTTP${status} average response time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,avg(responsetime) as \"平均\",top_path\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and ${status}\r\nGROUP BY time,top_path\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "TOP_Path HTTP${status} QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "\tSELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time, top_path, count() / ${cal_interval} AS avgqps\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and ${status}\r\n\tGROUP BY time, top_path\r\n  order by time"
    }
   ]
  },
  {
   "title": "TOP_Path HTTP${status} P90 response time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,quantileExact(0.90)(responsetime) as P90,top_path\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and ${status}\r\nGROUP BY time,top_path\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "The amount of data returned by TOP_Path per minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT toStartOfMinute(timestamp) AS time, top_path,sum(response_length) as \"返回量\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain}\r\nGROUP BY time, top_path\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "HTTP${status} request sources TOP30",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "\tSELECT\r\n\t  referer as Referer, \r\n    COUNT() as \"PV\", COUNT(DISTINCT client_ip) as \"UV\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\n\tGROUP BY referer\r\n  order by COUNT() DESC\r\n\tLIMIT 30;"
    }
   ]
  },
  {
   "title": "HTTP${status} Requests per URI TOP30",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "\tSELECT\r\n\t  `path` as \"request_path\", COUNT() AS PV, COUNT(DISTINCT client_ip) as \"UV\",avg(responsetime) as \"avg_resp_time\",avg(response_length) as \"avg_return\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\n\tGROUP BY `path`\r\n  order by PV DESC\r\n\tLIMIT 30;"
    }
   ]
  },
  {
   "title": "HTTP${status} returns the top 30 data volumes",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "\tSELECT\r\n\t  `path` as \"request_path\",avg(response_length) as \"avg_return\", avg(responsetime) as \"avg_resp_time\",COUNT() AS PV, COUNT(DISTINCT client_ip) as \"UV\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\n\tGROUP BY `path`\r\n  order by \"avg_return\" DESC\r\n\tLIMIT 30;"
    }
   ]
  },
  {
   "title": "User and region analysis [$domain]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 }
  },
  {
   "title": "HTTP${status} User IP Request Volume TOP30",
   "type": "table",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "\tSELECT\r\n\t  client_ip as \"USERIP\", \r\n    COUNT() AS PV, COUNT(DISTINCT `path`) as \"URL Count\",sum(response_length) as \"Received data volume\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\n\tGROUP BY client_ip\r\n  order by PV DESC\r\n\tLIMIT 30;"
    }
   ]
  },
  {
   "title": "Average HTTP${status} response time and PV in each city in the last minute",
   "type": "table",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT client_region as \"Province\",client_city as \"City\",avg(responsetime) as \"resp_time\",count() as \"PV\",COUNT(DISTINCT client_ip) as UV\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\ngroup by client_region,client_city"
    }
   ]
  },
  {
   "title": "HTTP${status} request province ratio",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 10, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\tSELECT\r\n\t  client_region, \r\n    COUNT() AS \"unknow\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\n\tGROUP BY client_region"
    }
   ]
  },
  {
   "title": "HTTP${status} request city ratio",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\tSELECT\r\n\t  client_city, \r\n    COUNT() AS \"unknow\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\n\tGROUP BY client_city"
    }
   ]
  },
  {
   "title": "Request operating system ratio",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\tSELECT\r\n\t  client_os_family, \r\n    COUNT() AS \"unknow\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain}\r\n\tGROUP BY client_os_family\r\n"
    }
   ]
  },
  {
   "title": "Requesting browsers TOP10",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 4, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\tSELECT\r\n\t  client_browser_family, \r\n    COUNT() AS \"unknow\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\n\tGROUP BY client_browser_family\r\n  order by COUNT() DESC\r\n\tLIMIT 10;"
    }
   ]
  },
  {
   "title": "Request device model TOP10",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 10, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\tSELECT\r\n\t  client_device_model, \r\n    COUNT() AS \"count\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and client_device_model != ''\r\n\tGROUP BY client_device_model\r\n  order by COUNT() DESC\r\n\tLIMIT 10;"
    }
   ]
  },
  {
   "title": "Request equipment brand TOP10",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\tSELECT\r\n\t  client_device_brand, \r\n    COUNT() AS \"count\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and client_device_brand != ''\r\n\tGROUP BY client_device_brand\r\n  order by COUNT() DESC\r\n\tLIMIT 10;"
    }
   ]
  },
  {
   "title": "HTTP${status}QPS by city",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 111 },
   "targets": [
    {
     "rawSql": "\tSELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time, client_city, count() / ${cal_interval} AS avgqps\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and ${status}\r\n\tGROUP BY time,client_city\r\n  order by time"
    }
   ]
  },
  {
   "title": "Average HTTP200 response time in each city (QPS>1)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,avg(responsetime) as \"avg\",client_city\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and ${status}\r\nGROUP BY time,client_city\r\nhaving count()/${cal_interval} > 1\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "HTTP200 P90 response time (QPS>1)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,quantileExact(0.90)(responsetime) as P90,client_city\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and ${status}\r\nGROUP BY time,client_city\r\nhaving count()/${cal_interval} > 1\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Specify user IP analysis: ${cip}[$domain]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 119 }
  },
  {
   "title": "HTTP${status} QPS of each backend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "\tSELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time, upstreamhost, count() / ${cal_interval} AS qps\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and ${status} and client_ip = '${cip}'\r\n\tGROUP BY time,upstreamhost\r\n  order by time"
    },
    {
     "rawSql": "\tSELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time, count() / ${cal_interval} AS qps,'Total'\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and ${status} and client_ip = '${cip}'\r\n\tGROUP BY time\r\n  order by time"
    }
   ]
  },
  {
   "title": "HTTP${status} response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "\r\nSELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,\r\n  quantileExact(0.99)(responsetime) as P99\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and ${status} and client_ip = '${cip}'\r\nGROUP BY time\r\nORDER BY time\r\n\r\n\r\n"
    },
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,\r\n  quantileExact(0.90)(responsetime) as P90\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and ${status} and client_ip = '${cip}'\r\nGROUP BY time\r\nORDER BY time\r\n\r\n\r\n"
    },
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,\r\n  quantileExact(0.50)(responsetime) as P50\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and ${status} and client_ip = '${cip}'\r\nGROUP BY time\r\nORDER BY time\r\n\r\n\r\n"
    },
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,\r\n  quantileExact(0.75)(responsetime) as P75\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and ${status} and client_ip = '${cip}'\r\nGROUP BY time\r\nORDER BY time\r\n\r\n\r\n"
    },
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,\r\n  quantileExact(0.95)(responsetime) as P95\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and ${status} and client_ip = '${cip}'\r\nGROUP BY time\r\nORDER BY time\r\n\r\n\r\n"
    },
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,avg(responsetime) as \"avg\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and ${status} and client_ip = '${cip}'\r\nGROUP BY time\r\nORDER BY time"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "\tSELECT\r\n\t  `top_path` as TOP_Path, COUNT() AS PV,avg(response_length) as \"avg_return\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and client_ip = '${cip}'\r\n\tGROUP BY `top_path`\r\n  order by COUNT() DESC\r\n"
    },
    {
     "rawSql": "\tSELECT\r\n\t  `top_path` as TOP_Path,avg(responsetime) as \"status response time\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status} and client_ip = '${cip}' \r\n\tGROUP BY `top_path`"
    },
    {
     "rawSql": "SELECT `top_path` as TOP_Path,\r\ncountIf(status >=400 and status < 500) as 4XX,\r\ncountIf(status>=500) as 5XX\r\nFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and client_ip = '${cip}'\r\nGROUP BY \r\n    `top_path`"
    }
   ]
  },
  {
   "title": "HTTP status code statistics (accumulated every minute)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  toStartOfMinute(timestamp) as time,\r\n  count() as value,toString(status) as \"state\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and client_ip = '${cip}'\r\nGROUP BY time,status\r\nORDER BY time\r\n"
    }
   ]
  },
  {
   "title": "HTTP${status} request details TOP100",
   "type": "table",
   "gridPos": { "h": 20, "w": 19, "x": 5, "y": 128 },
   "targets": [
    {
     "rawSql": "\r\nSELECT timestamp, status, request_method, domain,path,query,server_ip,upstreamhost,responsetime,upstreamtime,request_length,response_length\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status} and client_ip = '${cip}' \r\n\r\norder by timestamp desc\r\nlimit 100\r\n"
    }
   ]
  },
  {
   "title": "IP region and device",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "\tSELECT\r\n    client_region,client_city\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and client_ip = '${cip}'\r\ngroup by client_region,client_city\r\nlimit 1"
    },
    {
     "rawSql": "\tSELECT\r\n    client_os_family\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and client_ip = '${cip}' and client_os_family != ''\r\ngroup by client_os_family\r\n"
    }
   ]
  },
  {
   "title": "PV ratio of each UA",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 2, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\tSELECT\r\n    count() as count, http_user_agent as UA\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and client_ip = '${cip}'\r\n\tGROUP BY http_user_agent\r\n\torder by count desc"
    }
   ]
  },
  {
   "title": "PV of each UA in the current period of time",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "\tSELECT\r\n    COUNT() AS PV, COUNT(DISTINCT `path`) as \"URL Count\",avg(responsetime) as \"avg_resp\",sum(response_length) as \"recv\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and client_ip = '${cip}'\r\n\tGROUP BY client_region,client_city,http_user_agent"
    }
   ]
  },
  {
   "title": "Specify interface analysis: $uri[$domain]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 148 }
  },
  {
   "title": "HTTP${status} QPS of each backend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "\tSELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time, upstreamhost, count() / ${cal_interval} AS qps\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(time) and ${server_ip} and ${domain} and ${status} and path='${uri}'\r\n\tGROUP BY time,upstreamhost\r\n  order by time"
    },
    {
     "rawSql": "\tSELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time, count() / ${cal_interval} AS qps,'Total'\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(time) and ${server_ip} and ${domain} and ${status} and path='${uri}'\r\n\tGROUP BY time\r\n  order by time"
    }
   ]
  },
  {
   "title": "HTTP${status} response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "\r\nSELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,\r\n  quantileExact(0.99)(responsetime) as P99\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and ${status} and path='${uri}'\r\nGROUP BY time\r\nORDER BY time\r\n\r\n\r\n"
    },
    {
     "rawSql": "\r\nSELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,\r\n  quantileExact(0.90)(responsetime) as P90\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and ${status} and path='${uri}'\r\nGROUP BY time\r\nORDER BY time\r\n\r\n\r\n"
    },
    {
     "rawSql": "\r\nSELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,\r\n  quantileExact(0.50)(responsetime) as P50\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and ${status} and path='${uri}'\r\nGROUP BY time\r\nORDER BY time\r\n\r\n\r\n"
    },
    {
     "rawSql": "\r\nSELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,\r\n  quantileExact(0.75)(responsetime) as P75\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and ${status} and path='${uri}'\r\nGROUP BY time\r\nORDER BY time\r\n\r\n\r\n"
    },
    {
     "rawSql": "\r\nSELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,\r\n  quantileExact(0.95)(responsetime) as P95\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and ${status} and path='${uri}'\r\nGROUP BY time\r\nORDER BY time\r\n\r\n\r\n"
    },
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,avg(responsetime) as \"avg\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and ${status} and path='${uri}'\r\nGROUP BY time\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Average HTTP${status} response time of each backend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,upstreamhost,avg(responsetime) as rt\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and ${status} and path='${uri}'\r\nGROUP BY time,upstreamhost\r\nORDER BY time"
    },
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,avg(responsetime) as rt, 'Total'\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and ${status} and path='${uri}'\r\nGROUP BY time\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "HTTP status code statistics (accumulated every minute)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  toStartOfMinute(timestamp) as time,\r\n  count() as value,toString(status) as \"状态\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(time) and ${server_ip} and ${domain} and ${status} and path='${uri}'\r\nGROUP BY time,status\r\nORDER BY time\r\n"
    }
   ]
  },
  {
   "title": "[$uri] HTTP${status} request details TOP100 (all charts on this page are related to this interface)",
   "type": "table",
   "gridPos": { "h": 19, "w": 20, "x": 4, "y": 157 },
   "targets": [
    {
     "rawSql": "\r\nSELECT timestamp, status, request_method, domain,query,server_ip,upstreamhost,responsetime,upstreamtime,request_length,response_length,client_ip,client_city\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status} and path='${uri}'\r\n\r\norder by timestamp desc\r\nlimit 100\r\n"
    }
   ]
  },
  {
   "title": "HTTP${status} request user IP TOP30",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 167 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "\tSELECT\r\n\t  client_ip as \"User IP\", \r\n    COUNT() AS PV, avg(responsetime) as \"avg_resp_time\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status} and path='${uri}'\r\n\tGROUP BY client_ip\r\n  order by PV DESC\r\n\tLIMIT 30;"
    }
   ]
  },
  { "title": "Request log details [$domain]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 176 } },
  {
   "title": "HTTP${status} request details (latest 500)",
   "type": "table",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 177 },
   "targets": [
    {
     "rawSql": "\r\nSELECT timestamp, status, request_method, domain,path,query,server_ip,upstreamhost,responsetime,upstreamtime,request_length,response_length,client_ip,client_city\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\n\r\norder by timestamp desc\r\nlimit 500\r\n"
    }
   ]
  }
 ]
}