{
 "title": "Cluster Overview",
 "description": "This is a modern 'Global View' dashboard for your Kubernetes cluster(s). Made for kube-prometheus-stack and take advantage of the latest Grafana features. GitHub repository: https://github.com/dotdc/grafana-dashboards-kubernetes",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster_id",
    "label": "Cluster",
    "query": "SELECT DISTINCT scope_id AS __value, \nCASE \n  WHEN c.name != '' THEN c.name\n  ELSE scope_id\nEND AS __text\nFROM data_scope \nLEFT JOIN clusters c ON scope_id  = c.id\nWHERE type = 'cluster'"
   },
   {
    "name": "cluster_id",
    "label": "ClusterID",
    "query": {
     "query": "label_values(originx_agent_ready,cluster_id)"
    }
   },
   { "name": "resolution", "label": "Resolution", "query": "1s, 15s, 30s, 1m, 3m, 5m" },
   {
    "name": "job_name",
    "label": "nodeExporter Job",
    "query": {
     "query": "label_values(node_cpu_seconds_total,job_name)"
    }
   },
   {
    "name": "cadvisor_job_name",
    "label": "cAdvisor Job",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total,job_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Cluster CPU Utilization",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum by (instance_name, cpu) (rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\",  job_name=\"$job_name\", cluster_id=~\"$cluster_id\"}[$__rate_interval])))",
     "legendFormat": "Real Linux"
    }
   ]
  },
  {
   "title": "Total Cluster Memory Utilization",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{ job_name=\"$job_name\", cluster_id=~\"$cluster_id\"} - node_memory_MemAvailable_bytes{ job_name=\"$job_name\", cluster_id=~\"$cluster_id\"}) / sum(max_over_time(node_memory_MemTotal_bytes{ job_name=\"$job_name\", cluster_id=~\"$cluster_id\"}[5m]))",
     "legendFormat": "Real Linux"
    }
   ]
  },
  {
   "title": "Namespaces",
   "type": "stat",
   "description": "Number of Namespaces",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(group by (namespace) (container_memory_rss{job_name=\"$cadvisor_job_name\", cluster_id=~\"$cluster_id\"}))"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "description": "Number of Nodes",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(group by (instance_name) (container_memory_rss{job_name=\"$cadvisor_job_name\", cluster_id=~\"$cluster_id\"}))"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\",  job_name=\"$job_name\", cluster_id=~\"$cluster_id\"}[$__rate_interval]))",
     "legendFormat": "Real Linux"
    },
    {
     "expr": "max_over_time(sum ((group by (instance_name,cpu) (node_cpu_seconds_total{job_name=\"$job_name\", cluster_id=~\"$cluster_id\"})))[5m])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "description": "RAM Usage",
   "gridPos": { "h": 5, "w": 9, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{ job_name=\"$job_name\", cluster_id=~\"$cluster_id\"} - node_memory_MemAvailable_bytes{ job_name=\"$job_name\", cluster_id=~\"$cluster_id\"})",
     "legendFormat": "Real Linux"
    },
    {
     "expr": "sum(max_over_time(node_memory_MemTotal_bytes{ job_name=\"$job_name\", cluster_id=~\"$cluster_id\"}[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "stat",
   "description": "Running Pod Count",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(group by (pod) (container_memory_rss{job_name=\"$cadvisor_job_name\", cluster_id=~\"$cluster_id\"}))"
    }
   ]
  },
  {
   "title": "Cluster CPU Utilization",
   "type": "timeseries",
   "description": "Cluster CPU Utilization",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(sum by (instance_name, cpu) (rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\",  job_name=\"$job_name\", cluster_id=~\"$cluster_id\"}[$__rate_interval])))",
     "legendFormat": "Linux"
    },
    {
     "expr": "1 - avg(rate(windows_cpu_time_total{mode=\"idle\", job_name=\"$job_name\", cluster_id=~\"$cluster_id\"}[$__rate_interval]))",
     "legendFormat": "Windows"
    }
   ]
  },
  {
   "title": "Cluster Memory Utilization",
   "type": "timeseries",
   "description": "Cluster Memory Utilization",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{ job_name=\"$job_name\", cluster_id=~\"$cluster_id\"} - node_memory_MemAvailable_bytes{ job_name=\"$job_name\", cluster_id=~\"$cluster_id\"}) / sum(node_memory_MemTotal_bytes{ job_name=\"$job_name\", cluster_id=~\"$cluster_id\"})",
     "legendFormat": "Linux"
    },
    {
     "expr": "sum(windows_os_visible_memory_bytes{ job_name=\"$job_name\", cluster_id=~\"$cluster_id\"} - windows_memory_available_bytes{ job_name=\"$job_name\", cluster_id=~\"$cluster_id\"}) / sum(windows_os_visible_memory_bytes{ job_name=\"$job_name\", cluster_id=~\"$cluster_id\"})",
     "legendFormat": "Windows"
    }
   ]
  },
  {
   "title": "Total Cluster Network Bandwidth (By Device)",
   "type": "timeseries",
   "description": "Global Network Utilization by Device, excluding common virtual devices to reduce noise (veth, azv, lxc, cali)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!~\"(veth|azv|lxc|cali).*\",  job_name=\"$job_name\", cluster_id=~\"$cluster_id\"}[$__rate_interval])) by (device)",
     "legendFormat": "Receive : {{ device }}"
    },
    {
     "expr": "- sum(rate(node_network_transmit_bytes_total{device!~\"(veth|azv|lxc|cali).*\",  job_name=\"$job_name\", cluster_id=~\"$cluster_id\"}[$__rate_interval])) by (device)",
     "legendFormat": "Send : {{ device }}"
    },
    {
     "expr": "sum(rate(windows_net_bytes_received_total{ job_name=\"$job_name\", cluster_id=~\"$cluster_id\"}[$__rate_interval])) by (nic)",
     "legendFormat": "Received : {{ nic }}"
    },
    {
     "expr": "- sum(rate(windows_net_bytes_sent_total{ job_name=\"$job_name\", cluster_id=~\"$cluster_id\"}[$__rate_interval])) by (nic)",
     "legendFormat": "Transmitted : {{ device }}"
    }
   ]
  },
  {
   "title": "Network Saturation - Packets Dropped",
   "type": "timeseries",
   "description": "Network Saturation - Packets Dropped",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_drop_total{ job_name=\"$job_name\", cluster_id=~\"$cluster_id\"}[$__rate_interval]))",
     "legendFormat": "Linux Packets dropped (receive)"
    },
    {
     "expr": "- sum(rate(node_network_transmit_drop_total{ job_name=\"$job_name\", cluster_id=~\"$cluster_id\"}[$__rate_interval]))",
     "legendFormat": "Linux Packets dropped (transmit)"
    },
    {
     "expr": "sum(rate(windows_net_packets_received_discarded_total{ job_name=\"$job_name\", cluster_id=~\"$cluster_id\"}[$__rate_interval]))",
     "legendFormat": "Windows Packets dropped (receive)"
    },
    {
     "expr": "- sum(rate(windows_net_packets_outbound_discarded_total{ job_name=\"$job_name\", cluster_id=~\"$cluster_id\"}[$__rate_interval]))",
     "legendFormat": "Windows Packets dropped (transmit)"
    }
   ]
  },
  { "title": "Node Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Node CPU Utilization",
   "type": "timeseries",
   "description": "CPU Utilization by Instance",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(sum by (instance_name, cpu) (rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\",  job_name=\"$job_name\", cluster_id=~\"$cluster_id\"}[$__rate_interval]))) by (instance_name)",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "avg(sum by (instance_name,core) (rate(windows_cpu_time_total{mode!=\"idle\",  job_name=\"$job_name\", cluster_id=~\"$cluster_id\"}[$__rate_interval]))) by (instance_name)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Node Memory Utilization",
   "type": "timeseries",
   "description": "Memory Utilization by Instance",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{ job_name=\"$job_name\", cluster_id=~\"$cluster_id\"} - node_memory_MemAvailable_bytes{ job_name=\"$job_name\", cluster_id=~\"$cluster_id\"}) by (instance_name)",
     "legendFormat": "{{ instance_name }}"
    },
    {
     "expr": "sum(windows_os_visible_memory_bytes{ job_name=\"$job_name\", cluster_id=~\"$cluster_id\"} - windows_memory_available_bytes{ job_name=\"$job_name\", cluster_id=~\"$cluster_id\"}) by (instance_name)",
     "legendFormat": "{{ instance_name }}"
    }
   ]
  },
  {
   "title": "Total Network Usage by Node",
   "type": "timeseries",
   "description": "Total Network Received with all virtual devices by instance, including virtual devices and loopback",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{ job_name=\"$job_name\", cluster_id=~\"$cluster_id\"}[$__rate_interval])) by (instance_name)",
     "legendFormat": "Receive: {{ instance_name }}"
    },
    {
     "expr": "- sum(rate(node_network_transmit_bytes_total{ job_name=\"$job_name\", cluster_id=~\"$cluster_id\"}[$__rate_interval])) by (instance_name)",
     "legendFormat": "Send: {{ instance_name }}"
    },
    {
     "expr": "sum(rate(windows_net_bytes_received_total{ job_name=\"$job_name\", cluster_id=~\"$cluster_id\"}[$__rate_interval])) by (instance_name)",
     "legendFormat": "Received bytes in {{ instance_name }}"
    },
    {
     "expr": "- sum(rate(windows_net_bytes_sent_total{ job_name=\"$job_name\", cluster_id=~\"$cluster_id\"}[$__rate_interval])) by (instance_name)",
     "legendFormat": "Transmitted bytes in {{ instance_name }}"
    }
   ]
  },
  {
   "title": "Network Usage by Node (Excluding Loopback/Virtual Devices)",
   "type": "timeseries",
   "description": "Network Received without loopback by instance",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!~\"(veth|azv|lxc|lo|cali).*\",  job_name=\"$job_name\", cluster_id=~\"$cluster_id\"}[$__rate_interval])) by (instance_name)",
     "legendFormat": "Received bytes in {{ instance_name }}"
    },
    {
     "expr": "- sum(rate(node_network_transmit_bytes_total{device!~\"(veth|azv|lxc|lo|cali).*\",  job_name=\"$job_name\", cluster_id=~\"$cluster_id\"}[$__rate_interval])) by (instance_name)",
     "legendFormat": "Transmitted bytes in {{ instance_name }}"
    },
    {
     "expr": "sum(rate(windows_net_bytes_received_total{nic!~\".*Virtual.*\", job_name=\"$job_name\", cluster_id=~\"$cluster_id\"}[$__rate_interval])) by (instance_name)",
     "legendFormat": "Received bytes in {{ instance_name }}"
    },
    {
     "expr": "- sum(rate(windows_net_bytes_sent_total{nic!~\".*Virtual.*\", job_name=\"$job_name\", cluster_id=~\"$cluster_id\"}[$__rate_interval])) by (instance_name)",
     "legendFormat": "Transmitted bytes in {{ instance_name }}"
    }
   ]
  },
  {
   "title": "Network Usage by Node (Loopback Only)",
   "type": "timeseries",
   "description": "Network Received (loopback only) by instance",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device=\"lo\",  job_name=\"$job_name\", cluster_id=~\"$cluster_id\"}[$__rate_interval])) by (instance_name)",
     "legendFormat": "Received bytes in {{ instance_name }}"
    },
    {
     "expr": "- sum(rate(node_network_transmit_bytes_total{device=\"lo\",  job_name=\"$job_name\", cluster_id=~\"$cluster_id\"}[$__rate_interval])) by (instance_name)",
     "legendFormat": "Transmitted bytes in {{ instance_name }}"
    }
   ]
  },
  {
   "title": "CPU Core Throttled Duration by Node",
   "type": "timeseries",
   "description": "CPU Core Throttled by instance, no data means sufficient CPU or no throttling",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_core_throttles_total{ job_name=\"$job_name\", cluster_id=~\"$cluster_id\"}[$__rate_interval])) by (instance_name)",
     "legendFormat": "{{ instance_name }}"
    }
   ]
  },
  { "title": "Namespace Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "CPU Usage by Namespace",
   "type": "timeseries",
   "description": "CPU Utilization by Namespace",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", job_name=\"$cadvisor_job_name\", cluster_id=~\"$cluster_id\"}[$__rate_interval])) by (namespace) OR (group by (namespace) (container_memory_rss{job_name=\"$cadvisor_job_name\", cluster_id=~\"$cluster_id\"}) * 0 ) ",
     "legendFormat": "{{ namespace }}"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{ job_name=\"$cadvisor_job_name\",id=~\".*docker.*\", cluster_id=~\"$cluster_id\"}[$__rate_interval])) by (namespace) OR (group by (namespace) (container_memory_rss{job_name=\"$cadvisor_job_name\",id=~\".*docker.*\", cluster_id=~\"$cluster_id\"}) * 0 ) ",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "CPU Throttled Duration by Namespace",
   "type": "timeseries",
   "description": "CPU Throttled Seconds by Namespace, no data means no throttling, implying sufficient CPU or no limits applied",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{image!=\"\", job_name=\"$cadvisor_job_name\", cluster_id=~\"$cluster_id\"}[$__rate_interval])) by (namespace) > 0",
     "legendFormat": "{{ namespace }}"
    },
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{job_name=\"$cadvisor_job_name\",id=~\".*docker.*\", cluster_id=~\"$cluster_id\"}[$__rate_interval])) by (namespace) > 0",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Network Usage by Namespace",
   "type": "timeseries",
   "description": "Network Received by Namespace",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace!=\"\",job_name=\"$cadvisor_job_name\", cluster_id=~\"$cluster_id\"}[$__rate_interval])) by (namespace)\nOR (group by (namespace) (container_memory_rss{job_name=\"$cadvisor_job_name\", cluster_id=~\"$cluster_id\"}) * 0 ) ",
     "legendFormat": "Receive : {{ namespace }}"
    },
    {
     "expr": "- (sum(rate(container_network_transmit_bytes_total{namespace!=\"\",job_name=\"$cadvisor_job_name\", cluster_id=~\"$cluster_id\"}[$__rate_interval])) by (namespace)\nOR (group by (namespace) (container_memory_rss{job_name=\"$cadvisor_job_name\", cluster_id=~\"$cluster_id\"}) * 0 ) )",
     "legendFormat": "Send : {{ namespace }}"
    }
   ]
  },
  {
   "title": "Memory Usage by Namespace",
   "type": "timeseries",
   "description": "Memory Utilization by Namespace",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\", job_name=\"$cadvisor_job_name\", cluster_id=~\"$cluster_id\"}) by (namespace)\n OR (group by (namespace) (container_memory_rss{job_name=\"$cadvisor_job_name\", cluster_id=~\"$cluster_id\"}) * 0 ) ",
     "legendFormat": "{{ namespace }}"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{job_name=\"$cadvisor_job_name\",id=~\".*docker.*\", cluster_id=~\"$cluster_id\"}) by (namespace)\n OR (group by (namespace) (container_memory_rss{job_name=\"$cadvisor_job_name\",id=~\".*docker.*\", cluster_id=~\"$cluster_id\"}) * 0 ) ",
     "legendFormat": "{{ namespace }}"
    }
   ]
  }
 ]
}