{
 "title": "Infrastructure Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster_id",
    "label": "Cluster",
    "query": "SELECT DISTINCT scope_id AS __value, \nCASE \n  WHEN c.name != '' THEN c.name\n  ELSE scope_id\nEND AS __text\nFROM data_scope \nLEFT JOIN clusters c ON scope_id  = c.id\nWHERE type = 'cluster'"
   },
   { "name": "service_type", "label": "QueryBy", "query": "K8S : .*, Application :  ," },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "query_result(group by (namespace) (container_memory_rss{job_name=\"$cadvisor_job_name\",namespace=~\"$service_type\", cluster_id=~\"$cluster_id\"}))"
    }
   },
   {
    "name": "pod",
    "label": "POD",
    "query": {
     "query": "query_result(group by (pod) (container_memory_rss{namespace=\"$namespace\",job_name=\"$cadvisor_job_name\", cluster_id=~\"$cluster_id\"}))"
    }
   },
   {
    "name": "service_name",
    "label": "Application Name",
    "query": {
     "query": "query_result(group by (svc_name) (kindling_span_trace_duration_nanoseconds_count{vm=\"$service_type\", cluster_id=~\"$cluster_id\"}) or group by (svc_name) (kindling_span_trace_duration_nanoseconds_count{pod=~\"$pod\",namespace=~\"$namespace\", cluster_id=~\"$cluster_id\"}))"
    }
   },
   {
    "name": "related_nodes",
    "label": "Related Nodes",
    "query": {
     "query": "query_result( group by (node_name) (container_memory_rss{job_name=\"integrations/kubernetes/cadvisor\",pod=~\"$pod\",pod!=\"\", cluster_id=~\"$cluster_id\"}) or group by (node_name) ( kindling_span_trace_duration_nanoseconds_count{svc_name=\"$service_name\",svc_name!=\"\", cluster_id=~\"$cluster_id\"}))"
    }
   },
   {
    "name": "resolution",
    "label": "Resolution",
    "query": "1s, 15s, 30s, 1m, 3m, 5m , 10m, 30m"
   },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   },
   {
    "name": "related_pid",
    "query": {
     "query": "label_values(kindling_span_trace_duration_nanoseconds_count{svc_name=~\"$service_name\", cluster_id=~\"$cluster_id\"},pid)"
    }
   },
   {
    "name": "jvm_instance",
    "label": "JVM Instance",
    "query": {
     "query": "query_result(jvm_cpu_count{host_name=~\"$pod\", cluster_id=~\"$cluster_id\"} or jvm_cpu_count{service_name=~\"$service_name\",vm=\"$service_type\", cluster_id=~\"$cluster_id\"})"
    }
   },
   { "name": "job_name", "label": "nodeExporter Job", "query": "integrations/unix" },
   {
    "name": "cadvisor_job_name",
    "label": "cAdvisor Job",
    "query": "integrations/kubernetes/cadvisor"
   }
  ]
 },
 "panels": [
  {
   "title": "Container CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container CPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$pod\", image!=\"\", container!=\"\", job_name=\"$cadvisor_job_name\", cluster_id=~\"$cluster_id\"}[$__rate_interval])) by (container,pod)",
       "legendFormat": "{{pod}}: {{ container }}"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$pod\", job_name=\"$cadvisor_job_name\",id=~\".*docker.*\", cluster_id=~\"$cluster_id\"}[$__rate_interval])) by (container,pod)",
       "legendFormat": "{{pod}}: {{ container }}"
      }
     ]
    },
    {
     "title": "Container CPU Throttling Time",
     "type": "timeseries",
     "description": "Container CPU Throttled Time (CPU Throttled seconds), no data means sufficient CPU or no throttling applied",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{namespace=~\"$namespace\", pod=~\"$pod\", image!=\"\", container!=\"\", job_name=\"$cadvisor_job_name\", cluster_id=~\"$cluster_id\"}[$__rate_interval])) by (container,pod)",
       "legendFormat": "{{pod}}:{{ container }}"
      },
      {
       "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{namespace=~\"$namespace\", pod=~\"$pod\", job_name=\"$cadvisor_job_name\",id=~\".*docker.*\", cluster_id=~\"$cluster_id\"}[$__rate_interval])) by (container,pod)",
       "legendFormat": "{{pod}}:{{ container }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Container Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container Memory Utilization",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$pod\", image!=\"\", container!=\"\", job_name=\"$cadvisor_job_name\", cluster_id=~\"$cluster_id\"}) by (container,pod)",
       "legendFormat": "{{pod}}: {{ container }}"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$pod\",job_name=\"$cadvisor_job_name\",id=~\".*docker.*\", cluster_id=~\"$cluster_id\"}) by (container,pod)",
       "legendFormat": "{{pod}}: {{ container }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Container Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read/Write Bytes per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (pod,container)(rate(container_fs_reads_bytes_total{namespace=\"$namespace\", pod=~\"$pod\", image!=\"\", container!=\"\", job_name=\"$cadvisor_job_name\", cluster_id=~\"$cluster_id\"}[$__rate_interval]))",
       "legendFormat": "Read {{pod}}:{{container}}"
      },
      {
       "expr": "- sum by (pod,container)(rate(container_fs_writes_bytes_total{namespace=\"$namespace\", pod=~\"$pod\", image!=\"\", container!=\"\", job_name=\"$cadvisor_job_name\", cluster_id=~\"$cluster_id\"}[$__rate_interval]))",
       "legendFormat": "Write {{pod}}:{{container}}"
      },
      {
       "expr": "sum by (pod,container)(rate(container_fs_reads_bytes_total{namespace=\"$namespace\", pod=~\"$pod\", job_name=\"$cadvisor_job_name\",id=~\".*docker.*\", cluster_id=~\"$cluster_id\"}[$__rate_interval]))",
       "legendFormat": "Read {{pod}}:{{container}}"
      },
      {
       "expr": "- sum by (pod,container)(rate(container_fs_writes_bytes_total{namespace=\"$namespace\", pod=~\"$pod\", job_name=\"$cadvisor_job_name\",id=~\".*docker.*\", cluster_id=~\"$cluster_id\"}[$__rate_interval]))",
       "legendFormat": "Write {{pod}}:{{container}}"
      }
     ]
    },
    {
     "title": "Read/Write Time per second",
     "type": "timeseries",
     "description": "This metric will be missing due to a cAdvisor defect with Docker as the container runtime.[#link](https://kubernetes.io/docs/tasks/administer-cluster/migrating-from-dockershim/check-if-dockershim-removal-affects-you/#some-filesystem-metrics-are-missing-and-the-metrics-format-is-different)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (pod,container)(rate(container_fs_read_seconds_total{namespace=\"$namespace\", pod=~\"$pod\", image!=\"\", container!=\"\", job_name=\"$cadvisor_job_name\", cluster_id=~\"$cluster_id\"}[$__rate_interval]))",
       "legendFormat": "Read {{pod}}:{{container}}"
      },
      {
       "expr": "- sum by (pod,container)(rate(container_fs_write_seconds_total{namespace=\"$namespace\", pod=~\"$pod\", image!=\"\", container!=\"\", job_name=\"$cadvisor_job_name\", cluster_id=~\"$cluster_id\"}[$__rate_interval]))",
       "legendFormat": "Write {{pod}}:{{container}}"
      }
     ]
    },
    {
     "title": "Read/Write Operations per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by (pod,container)(rate(container_fs_reads_total{namespace=\"$namespace\", pod=~\"$pod\", image!=\"\", container!=\"\", job_name=\"$cadvisor_job_name\", cluster_id=~\"$cluster_id\"}[$__rate_interval]))",
       "legendFormat": "Read {{pod}}:{{container}}"
      },
      {
       "expr": "- sum by (pod,container)(rate(container_fs_writes_total{namespace=\"$namespace\", pod=~\"$pod\", image!=\"\", container!=\"\", job_name=\"$cadvisor_job_name\", cluster_id=~\"$cluster_id\"}[$__rate_interval]))",
       "legendFormat": "Write {{pod}}:{{container}}"
      },
      {
       "expr": "sum by (pod,container)(rate(container_fs_reads_total{namespace=\"$namespace\", pod=~\"$pod\",job_name=\"$cadvisor_job_name\",id=~\".*docker.*\", cluster_id=~\"$cluster_id\"}[$__rate_interval]))",
       "legendFormat": "Read {{pod}}:{{container}}"
      },
      {
       "expr": "- sum by (pod,container)(rate(container_fs_writes_total{namespace=\"$namespace\", pod=~\"$pod\",  job_name=\"$cadvisor_job_name\",id=~\".*docker.*\", cluster_id=~\"$cluster_id\"}[$__rate_interval]))",
       "legendFormat": "Write {{pod}}:{{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Container Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "RTT with Downstream Service",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "kindling_network_rtt{src_namespace=\"$namespace\", src_pod=~\"$pod\", cluster_id=~\"$cluster_id\"}",
       "legendFormat": "{{src_pod}} -> {{dst_pod}} ({{dst_ip}})"
      }
     ]
    },
    {
     "title": "Network Bandwidth Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"$pod\", job_name=\"$cadvisor_job_name\", cluster_id=~\"$cluster_id\"}[$__rate_interval]))",
       "legendFormat": "Receive"
      },
      {
       "expr": "- sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"$pod\", job_name=\"$cadvisor_job_name\", cluster_id=~\"$cluster_id\"}[$__rate_interval]))",
       "legendFormat": "Send"
      }
     ]
    },
    {
     "title": "Packet Transmission Rate",
     "type": "timeseries",
     "description": "Number of packets sent and received per second 1 p/s = 1000 mp/s",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_packets_total{namespace=\"$namespace\", pod=~\"$pod\", job_name=\"$cadvisor_job_name\", cluster_id=~\"$cluster_id\"}[$__rate_interval]))",
       "legendFormat": "Receive"
      },
      {
       "expr": "- sum(rate(container_network_transmit_packets_total{namespace=\"$namespace\", pod=~\"$pod\", job_name=\"$cadvisor_job_name\", cluster_id=~\"$cluster_id\"}[$__rate_interval]))",
       "legendFormat": "Send"
      }
     ]
    },
    {
     "title": "Packet Loss Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_packets_dropped_total{namespace=\"$namespace\", pod=~\"$pod\", job_name=\"$cadvisor_job_name\", cluster_id=~\"$cluster_id\"}[$__rate_interval]))",
       "legendFormat": "Received"
      },
      {
       "expr": "- sum(rate(container_network_transmit_packets_dropped_total{namespace=\"$namespace\", pod=~\"$pod\", job_name=\"$cadvisor_job_name\", cluster_id=~\"$cluster_id\"}[$__rate_interval]))",
       "legendFormat": "Transmitted"
      }
     ]
    },
    {
     "title": "Network Error Packet Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_errors_total{namespace=\"$namespace\", pod=~\"$pod\", job_name=\"$cadvisor_job_name\", cluster_id=~\"$cluster_id\"}[$__rate_interval]))",
       "legendFormat": "Receive"
      },
      {
       "expr": "- sum(rate(container_network_transmit_errors_total{namespace=\"$namespace\", pod=~\"$pod\", job_name=\"$cadvisor_job_name\", cluster_id=~\"$cluster_id\"}[$__rate_interval]))",
       "legendFormat": "Send"
      }
     ]
    }
   ]
  },
  {
   "title": "Application Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "RTT with Downstream Service",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "kindling_network_rtt{node_name=~\"$related_nodes\", pid=~\"$related_pid\", cluster_id=~\"$cluster_id\"}",
       "legendFormat": "{{src_pod}} ({{src_ip}}) -> {{dst_pod}} ({{dst_ip}}) "
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Instance Status ($jvm_instance)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "repeat": "jvm_instance",
   "collapsed": true,
   "panels": [
    {
     "title": "Basic Information",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "jvm_cpu_count{instance=\"$jvm_instance\", cluster_id=~\"$cluster_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average CPU Utilization (Cores)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(jvm_cpu_time_seconds_total{instance=\"$jvm_instance\", cluster_id=~\"$cluster_id\"}[$__rate_interval])",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Class Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "jvm_class_count{instance=\"$jvm_instance\", cluster_id=~\"$cluster_id\"}",
       "legendFormat": "Loaded Class"
      },
      {
       "expr": "jvm_class_unloaded_total{instance=\"$jvm_instance\", cluster_id=~\"$cluster_id\"}",
       "legendFormat": "UnLoaded Class"
      },
      {
       "expr": "jvm_class_count{instance=\"$jvm_instance\", cluster_id=~\"$cluster_id\"}",
       "legendFormat": "Class Count"
      }
     ]
    },
    {
     "title": "Heap Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=~\"$jvm_instance\",jvm_memory_type=\"heap\", cluster_id=~\"$cluster_id\"}",
       "legendFormat": "Used: {{jvm_memory_pool_name}}"
      },
      {
       "expr": "jvm_memory_limit{instance=~\"$jvm_instance\",jvm_memory_type=\"heap\", cluster_id=~\"$cluster_id\"}",
       "legendFormat": "Limit: {{jvm_memory_pool_name}}"
      }
     ]
    },
    {
     "title": "Non-Heap Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=~\"$jvm_instance\",jvm_memory_type=\"non_heap\", cluster_id=~\"$cluster_id\"}",
       "legendFormat": "Used: {{jvm_memory_pool_name}}"
      },
      {
       "expr": "jvm.memory.limit{instance=~\"$jvm_instance\",jvm_memory_type=\"non_heap\", cluster_id=~\"$cluster_id\"}",
       "legendFormat": "Limit: {{jvm_memory_pool_name}}"
      }
     ]
    },
    {
     "title": "Allocated Heap Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$jvm_instance\",jvm_memory_type=\"heap\", cluster_id=~\"$cluster_id\"}",
       "legendFormat": "{{jvm_memory_pool_name}}"
      }
     ]
    },
    {
     "title": "Allocated Non-Heap Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$jvm_instance\",jvm_memory_type=\"non_heap\", cluster_id=~\"$cluster_id\"}",
       "legendFormat": "{{jvm_memory_pool_name}}"
      }
     ]
    },
    {
     "title": "GC Operations Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(jvm_gc_duration_seconds_count{instance=\"$jvm_instance\", cluster_id=~\"$cluster_id\"}[$__interval])",
       "legendFormat": "{{jvm_gc_name}}:{{jvm_gc_action}}"
      }
     ]
    },
    {
     "title": "Total GC Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "increase(jvm_gc_duration_seconds_sum{instance=\"$jvm_instance\", cluster_id=~\"$cluster_id\"}[$__interval])",
       "legendFormat": "{{jvm_gc_name}}:{{jvm_gc_action}}"
      }
     ]
    },
    {
     "title": "Daemon Thread State Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "sum(jvm_thread_count{instance=\"$jvm_instance\",jvm_thread_daemon=\"true\", cluster_id=~\"$cluster_id\"})",
       "legendFormat": "total"
      },
      {
       "expr": "jvm_thread_count{instance=\"$jvm_instance\",jvm_thread_daemon=\"true\",jvm_thread_state!=\"\", cluster_id=~\"$cluster_id\"}",
       "legendFormat": "{{jvm_thread_state}}"
      }
     ]
    },
    {
     "title": "Non-Daemon Thread State Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "targets": [
      {
       "expr": "sum(jvm_thread_count{instance=\"$jvm_instance\",jvm_thread_daemon=\"false\", cluster_id=~\"$cluster_id\"})",
       "legendFormat": "total"
      },
      {
       "expr": "jvm_thread_count{instance=\"$jvm_instance\",jvm_thread_daemon=\"false\",jvm_thread_state!=\"\", cluster_id=~\"$cluster_id\"}",
       "legendFormat": "{{jvm_thread_state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "$related_nodes - Host Status Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "repeat": "related_nodes"
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance_name=~\"${related_nodes, cluster_id=~\"$cluster_id\"}\",job_name=\"$job_name\", mode=\"system\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance_name=~\"${related_nodes, cluster_id=~\"$cluster_id\"}\",job_name=\"$job_name\"}) by (cpu)))",
     "legendFormat": "System - System processes running in the kernel"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance_name=~\"${related_nodes, cluster_id=~\"$cluster_id\"}\",job_name=\"$job_name\", mode=\"user\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance_name=~\"${related_nodes, cluster_id=~\"$cluster_id\"}\",job_name=\"$job_name\"}) by (cpu)))",
     "legendFormat": "User - User space processes"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance_name=~\"${related_nodes, cluster_id=~\"$cluster_id\"}\",job_name=\"$job_name\", mode=\"nice\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance_name=~\"${related_nodes, cluster_id=~\"$cluster_id\"}\",job_name=\"$job_name\"}) by (cpu)))",
     "legendFormat": "Nice - Niced processes running in user space"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance_name=~\"${related_nodes, cluster_id=~\"$cluster_id\"}\",job_name=\"$job_name\", mode=\"iowait\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance_name=~\"${related_nodes, cluster_id=~\"$cluster_id\"}\",job_name=\"$job_name\"}) by (cpu)))",
     "legendFormat": "Iowait - IO Wait Time"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance_name=~\"${related_nodes, cluster_id=~\"$cluster_id\"}\",job_name=\"$job_name\", mode=\"irq\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance_name=~\"${related_nodes, cluster_id=~\"$cluster_id\"}\",job_name=\"$job_name\"}) by (cpu)))",
     "legendFormat": "Irq - Servicing interrupts"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance_name=~\"${related_nodes, cluster_id=~\"$cluster_id\"}\",job_name=\"$job_name\", mode=\"softirq\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance_name=~\"${related_nodes, cluster_id=~\"$cluster_id\"}\",job_name=\"$job_name\"}) by (cpu)))",
     "legendFormat": "Softirq - Handling soft interrupts"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance_name=~\"${related_nodes, cluster_id=~\"$cluster_id\"}\",job_name=\"$job_name\", mode=\"steal\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance_name=~\"${related_nodes, cluster_id=~\"$cluster_id\"}\",job_name=\"$job_name\"}) by (cpu)))",
     "legendFormat": "Steal - Time spent running other OSs in virtualization"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance_name=~\"${related_nodes, cluster_id=~\"$cluster_id\"}\",job_name=\"$job_name\", mode=\"idle\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance_name=~\"${related_nodes, cluster_id=~\"$cluster_id\"}\",job_name=\"$job_name\"}) by (cpu)))",
     "legendFormat": "Idle - Idle Time"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance_name=~\"${related_nodes, cluster_id=~\"$cluster_id\"}\",job_name=\"$job_name\"} - node_memory_MemFree_bytes{instance_name=~\"${related_nodes, cluster_id=~\"$cluster_id\"}\",job_name=\"$job_name\"} - node_memory_Buffers_bytes{instance_name=~\"${related_nodes, cluster_id=~\"$cluster_id\"}\",job_name=\"$job_name\"} - node_memory_Cached_bytes{instance_name=~\"${related_nodes, cluster_id=~\"$cluster_id\"}\",job_name=\"$job_name\"} - node_memory_Slab_bytes{instance_name=~\"${related_nodes, cluster_id=~\"$cluster_id\"}\",job_name=\"$job_name\"} - node_memory_PageTables_bytes{instance_name=~\"${related_nodes, cluster_id=~\"$cluster_id\"}\",job_name=\"$job_name\"} - node_memory_SwapCached_bytes{instance_name=~\"${related_nodes, cluster_id=~\"$cluster_id\"}\",job_name=\"$job_name\"}",
     "legendFormat": "App - Application usage in user space"
    },
    {
     "expr": "node_memory_PageTables_bytes{instance_name=~\"${related_nodes, cluster_id=~\"$cluster_id\"}\",job_name=\"$job_name\"}",
     "legendFormat": "PageTables - Memory used for virtual-to-physical memory mapping"
    },
    {
     "expr": "node_memory_SwapCached_bytes{instance_name=~\"${related_nodes, cluster_id=~\"$cluster_id\"}\",job_name=\"$job_name\"}",
     "legendFormat": "SwapCache - Memory for pages retrieved from swap but not yet modified"
    },
    {
     "expr": "node_memory_Slab_bytes{instance_name=~\"${related_nodes, cluster_id=~\"$cluster_id\"}\",job_name=\"$job_name\"}",
     "legendFormat": "Slab - Kernel memory used to cache data structures like inode, dentry"
    },
    {
     "expr": "node_memory_Cached_bytes{instance_name=~\"${related_nodes, cluster_id=~\"$cluster_id\"}\",job_name=\"$job_name\"}",
     "legendFormat": "Cache - Open file cache"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance_name=~\"${related_nodes, cluster_id=~\"$cluster_id\"}\",job_name=\"$job_name\"}",
     "legendFormat": "Buffers - Block device (e.g., hard disk) cache"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance_name=~\"${related_nodes, cluster_id=~\"$cluster_id\"}\",job_name=\"$job_name\"}",
     "legendFormat": "Unused - Unallocated memory"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance_name=~\"${related_nodes, cluster_id=~\"$cluster_id\"}\",job_name=\"$job_name\"} - node_memory_SwapFree_bytes{instance_name=~\"${related_nodes, cluster_id=~\"$cluster_id\"}\",job_name=\"$job_name\"})",
     "legendFormat": "Swap - Used swap space"
    },
    {
     "expr": "node_memory_HardwareCorrupted_bytes{instance_name=~\"${related_nodes, cluster_id=~\"$cluster_id\"}\",job_name=\"$job_name\"}",
     "legendFormat": "Hardware Corrupted - Amount of RAM marked as damaged/not working by kernel"
    }
   ]
  },
  {
   "title": "Network Transfer Rate (Excluding Virtual and Loopback Interfaces)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance_name=~\"${related_nodes, cluster_id=~\"$cluster_id\"}\",job_name=\"$job_name\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance_name=~\"${related_nodes, cluster_id=~\"$cluster_id\"}\",job_name=\"$job_name\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "File Descriptor Open Count",
   "type": "timeseries",
   "description": "File Descriptor Open Count",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_filefd_maximum{instance_name=~\"${related_nodes, cluster_id=~\"$cluster_id\"}\",job_name=\"$job_name\"}",
     "legendFormat": "Maximum Limit"
    },
    {
     "expr": "node_filefd_allocated{instance_name=~\"${related_nodes, cluster_id=~\"$cluster_id\"}\",job_name=\"$job_name\"}",
     "legendFormat": "Current Value"
    }
   ]
  },
  {
   "title": "Disk Operations Count",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance_name=~\"${related_nodes, cluster_id=~\"$cluster_id\"}\",job_name=\"$job_name\",device=~\"$diskdevices\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Read"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance_name=~\"${related_nodes, cluster_id=~\"$cluster_id\"}\",job_name=\"$job_name\",device=~\"$diskdevices\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Write"
    }
   ]
  },
  {
   "title": "Disk Read/Write Rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance_name=~\"${related_nodes, cluster_id=~\"$cluster_id\"}\",job_name=\"$job_name\",device=~\"$diskdevices\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance_name=~\"${related_nodes, cluster_id=~\"$cluster_id\"}\",job_name=\"$job_name\",device=~\"$diskdevices\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Write"
    }
   ]
  },
  {
   "title": "Filesystem Free Space",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{instance_name=~\"${related_nodes, cluster_id=~\"$cluster_id\"}\",job_name=\"$job_name\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}} - Free Space"
    },
    {
     "expr": "node_filesystem_size_bytes{instance_name=~\"${related_nodes, cluster_id=~\"$cluster_id\"}\",job_name=\"$job_name\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}} - Total Size"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance_name=~\"${related_nodes, cluster_id=~\"$cluster_id\"}\",job_name=\"$job_name\",device!~'rootfs'} - node_filesystem_avail_bytes{instance_name=~\"${related_nodes, cluster_id=~\"$cluster_id\"}\",job_name=\"$job_name\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "I/O Utilization",
   "type": "timeseries",
   "description": "The proportion of total time spent on I/O operations, reflecting the system's busyness when handling I/O tasks",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance_name=~\"${related_nodes, cluster_id=~\"$cluster_id\"}\",job_name=\"$job_name\",device=~\"$diskdevices\"} [$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}