{
 "title": "Originx Polaris Metrics(Container Level)",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(kindling_span_trace_duration_nanoseconds_count,svc_name)"
    }
   },
   {
    "name": "container_id",
    "label": "ContainerID",
    "query": {
     "query": "label_values(kindling_span_trace_duration_nanoseconds_count{svc_name=\"$service_name\"},container_id)"
    }
   },
   {
    "name": "content_key",
    "label": "Endpoints",
    "query": {
     "query": "label_values(kindling_span_trace_duration_nanoseconds_count{svc_name=~\"$service_name\"},content_key)"
    }
   },
   {
    "name": "interval",
    "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "RED Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (content_key, svc_name) (increase(kindling_span_trace_duration_nanoseconds_count{svc_name=~\"$service_name\", content_key=~\"$content_key\", container_id=~\"$container_id\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (svc_name, content_key) (increase(kindling_span_trace_duration_nanoseconds_count{is_error=\"false\", svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\"}[$interval]))/sum by (svc_name, content_key) (increase(kindling_span_trace_duration_nanoseconds_count{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\"}[$interval])) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg. Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (svc_name, content_key) (increase(kindling_span_trace_duration_nanoseconds_sum{svc_name=~\"$service_name\", content_key=~\"$content_key\", container_id=~\"$container_id\"}[$interval]))/sum by (svc_name, content_key) (increase(kindling_span_trace_duration_nanoseconds_count{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\"}[$interval]))/1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration Percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_span_trace_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\", container_id=~\"$container_id\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "P90: Service={{svc_name}}, Endpoint={{content_key}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kindling_span_trace_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "P95: Service={{svc_name}}, Endpoint={{content_key}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kindling_span_trace_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "P99: Service={{svc_name}}, Endpoint={{content_key}}"
    }
   ]
  },
  { "title": "Request Polaris Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Polaris Metrics Comparison",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_span_trace_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "P90 Duration"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_profiling_net_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "Net P90"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_profiling_epoll_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "Epoll P90"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_profiling_file_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "FileIO P90"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_profiling_futex_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "Futex/GC P90"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_profiling_cpu_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "onCPU P90"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_profiling_runq_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "Runqueue P90"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_profiling_other_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "Other P90"
    }
   ]
  },
  {
   "title": "Is network ok? Check the dependency latency.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_profiling_net_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\"}[$interval])) by (svc_name, content_key, vmrange)) + histogram_quantile(0.9, sum(rate(kindling_profiling_epoll_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "{{svc_name}}'s Dependency P90 Latency"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_span_trace_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "{{svc_name}}'s Response P90 Duration"
    }
   ]
  },
  {
   "title": "Is the CPU limit sufficient?",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_profiling_runq_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "CPU schedule latency"
    },
    {
     "expr": "sum by (content_key, svc_name) (increase(kindling_span_trace_duration_nanoseconds_count{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\"}[$interval]))",
     "legendFormat": "Request Count"
    }
   ]
  },
  {
   "title": "Whether futex latency affects QPS? ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_profiling_futex_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "Futex P90 Latency"
    },
    {
     "expr": "sum by (content_key, svc_name) (increase(kindling_span_trace_duration_nanoseconds_count{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\"}[$interval]))",
     "legendFormat": "Request Count"
    }
   ]
  },
  {
   "title": "Average onCPU time per request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by (content_key, svc_name) (increase(kindling_profiling_cpu_duration_nanoseconds_sum{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\"}[$interval]))/sum by (content_key, svc_name) (increase(kindling_profiling_cpu_duration_nanoseconds_count{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P90 onCPU time per request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_profiling_cpu_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average time wait for network per request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by (content_key, svc_name) (increase(kindling_profiling_net_duration_nanoseconds_sum{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\"}[$interval]))/sum by (content_key, svc_name) (increase(kindling_profiling_net_duration_nanoseconds_count{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P90 time wait for network per request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_profiling_net_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average time wait for epoll network per request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by (content_key, svc_name) (increase(kindling_profiling_epoll_duration_nanoseconds_sum{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\"}[$interval]))/sum by (content_key, svc_name) (increase(kindling_profiling_epoll_duration_nanoseconds_count{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P90 time wait for epoll network per request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_profiling_epoll_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average time wait for futex/GC per request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by (content_key, svc_name) (increase(kindling_profiling_futex_duration_nanoseconds_sum{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\"}[$interval]))/sum by (content_key, svc_name) (increase(kindling_profiling_futex_duration_nanoseconds_count{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P90 time wait for futex/GC per request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_profiling_futex_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average time wait for CPU scheduling per request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by (content_key, svc_name) (increase(kindling_profiling_runq_duration_nanoseconds_sum{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\"}[$interval]))/sum by (content_key, svc_name) (increase(kindling_profiling_runq_duration_nanoseconds_count{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P90 time wait for CPU scheduling per request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_profiling_runq_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average time wait for file IO per request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by (content_key, svc_name) (increase(kindling_profiling_file_duration_nanoseconds_sum{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\"}[$interval]))/sum by (content_key, svc_name) (increase(kindling_profiling_file_duration_nanoseconds_count{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P90 time wait for file IO per request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_profiling_file_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average time wait for other resources per request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by (content_key, svc_name) (increase(kindling_profiling_other_duration_nanoseconds_sum{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\"}[$interval]))/sum by (content_key, svc_name) (increase(kindling_profiling_other_duration_nanoseconds_count{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}