{
 "title": "Originx Polaris Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(kindling_span_trace_duration_nanoseconds_count,svc_name)"
    }
   },
   {
    "name": "content_key",
    "label": "Endpoint",
    "query": {
     "query": "label_values(kindling_span_trace_duration_nanoseconds_count{svc_name=~\"$service_name\"},content_key)"
    }
   },
   {
    "name": "interval",
    "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "RED Metric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (content_key, svc_name) (increase(kindling_span_trace_duration_nanoseconds_count{svc_name=~\"$service_name\", content_key=~\"$content_key\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (svc_name, content_key) (increase(kindling_span_trace_duration_nanoseconds_count{is_error=\"false\", svc_name=~\"$service_name\", content_key=~\"$content_key\"}[$interval]))/sum by (svc_name, content_key) (increase(kindling_span_trace_duration_nanoseconds_count{svc_name=~\"$service_name\", content_key=~\"$content_key\"}[$interval])) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Response Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (svc_name, content_key) (increase(kindling_span_trace_duration_nanoseconds_sum{svc_name=~\"$service_name\", content_key=~\"$content_key\"}[$interval]))/sum by (svc_name, content_key) (increase(kindling_span_trace_duration_nanoseconds_count{svc_name=~\"$service_name\", content_key=~\"$content_key\"}[$interval]))/1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Latency Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_span_trace_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "P90: Service Name={{svc_name}}, Request Endpoint={{content_key}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kindling_span_trace_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "P95: Service Name={{svc_name}}, Request Endpoint={{content_key}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kindling_span_trace_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "P99: Service Name={{svc_name}}, Request Endpoint={{content_key}}"
    }
   ]
  },
  { "title": "Polaris metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Polaris Comprehensive Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_span_trace_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "Latency"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_profiling_net_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "net"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_profiling_epoll_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "Asynchronous Network"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_profiling_file_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "File IO"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_profiling_futex_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "Lock or GC"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_profiling_cpu_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "CPU"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_profiling_runq_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "RUNQ"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_profiling_other_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "OTHER"
    }
   ]
  },
  {
   "title": "Quickly Determine If It's a Network Issue: Just Compare Application and Downstream Applications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_profiling_net_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\"}[$interval])) by (svc_name, content_key, vmrange)) + histogram_quantile(0.9, sum(rate(kindling_profiling_epoll_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "{{svc_name}} External Call Duration"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_span_trace_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "{{svc_name}} Latency"
    }
   ]
  },
  {
   "title": "Quickly Determine If Container Specifications Need to Be Upgraded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_profiling_runq_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "CPU Resource Waiting Duration"
    },
    {
     "expr": "sum by (content_key, svc_name) (increase(kindling_span_trace_duration_nanoseconds_count{svc_name=~\"$service_name\", content_key=~\"$content_key\"}[$interval]))",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "Average CPU Execution Time Per Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by (content_key, svc_name) (increase(kindling_profiling_cpu_duration_nanoseconds_sum{svc_name=~\"$service_name\", content_key=~\"$content_key\"}[$interval]))/sum by (content_key, svc_name) (increase(kindling_profiling_cpu_duration_nanoseconds_count{svc_name=~\"$service_name\", content_key=~\"$content_key\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Network Time Per Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by (content_key, svc_name) (increase(kindling_profiling_net_duration_nanoseconds_sum{svc_name=~\"$service_name\", content_key=~\"$content_key\"}[$interval]))/sum by (content_key, svc_name) (increase(kindling_profiling_net_duration_nanoseconds_count{svc_name=~\"$service_name\", content_key=~\"$content_key\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "90th Percentile CPU Execution Time Per Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_profiling_cpu_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "90th Percentile Network Time Per Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_profiling_net_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Epoll Network Time Per Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by (content_key, svc_name) (increase(kindling_profiling_epoll_duration_nanoseconds_sum{svc_name=~\"$service_name\", content_key=~\"$content_key\"}[$interval]))/sum by (content_key, svc_name) (increase(kindling_profiling_epoll_duration_nanoseconds_count{svc_name=~\"$service_name\", content_key=~\"$content_key\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Lock Wait or GC Time Per Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by (content_key, svc_name) (increase(kindling_profiling_futex_duration_nanoseconds_sum{svc_name=~\"$service_name\", content_key=~\"$content_key\"}[$interval]))/sum by (content_key, svc_name) (increase(kindling_profiling_futex_duration_nanoseconds_count{svc_name=~\"$service_name\", content_key=~\"$content_key\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "90th Percentile Epoll Network Time Per Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_profiling_epoll_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "90th Percentile Lock Wait or GC Time Per Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_profiling_futex_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Time Waiting for Other Resources Per Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by (content_key, svc_name) (increase(kindling_profiling_other_duration_nanoseconds_sum{svc_name=~\"$service_name\", content_key=~\"$content_key\"}[$interval]))/sum by (content_key, svc_name) (increase(kindling_profiling_other_duration_nanoseconds_count{svc_name=~\"$service_name\", content_key=~\"$content_key\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Time Waiting for CPU Scheduling Per Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by (content_key, svc_name) (increase(kindling_profiling_runq_duration_nanoseconds_sum{svc_name=~\"$service_name\", content_key=~\"$content_key\"}[$interval]))/sum by (content_key, svc_name) (increase(kindling_profiling_runq_duration_nanoseconds_count{svc_name=~\"$service_name\", content_key=~\"$content_key\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average File Read/Write Time Per Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by (content_key, svc_name) (increase(kindling_profiling_file_duration_nanoseconds_sum{svc_name=~\"$service_name\", content_key=~\"$content_key\"}[$interval]))/sum by (content_key, svc_name) (increase(kindling_profiling_file_duration_nanoseconds_count{svc_name=~\"$service_name\", content_key=~\"$content_key\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "90th Percentile Time Waiting for CPU Scheduling Per Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_profiling_runq_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "90th Percentile File Read/Write Time Per Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_profiling_file_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}