{
 "title": "Originx Data Self Monit",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node_name",
    "label": "Node",
    "query": {
     "query": "label_values(originx_agent_ready,node_name)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kindling_span_trace_duration_nanoseconds_count{node_name=~\"$node_name\"},pod)"
    }
   },
   {
    "name": "interval",
    "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "DataSource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Event count of txIn and txout - Ebpf Agent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (pod) (increase(originx_sr_tx_event_count{node_name=~\"$node_name\", pod=~\"$pod\", event_name=~\"txin\"}[$interval]))",
     "legendFormat": "{{pod}}_txin"
    },
    {
     "expr": "sum by (pod) (increase(originx_sr_tx_event_count{node_name=~\"$node_name\", pod=~\"$pod\", event_name=~\"txout\"}[$interval]))",
     "legendFormat": "{{pod}}_txout"
    }
   ]
  },
  {
   "title": "Event count of java  lock - Ebpf Agent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (pod) (increase(originx_sr_tx_event_count{node_name=~\"$node_name\", pod=~\"$pod\", event_name=\"futex\"}[$interval])>0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Trace Related Datas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Polaris Profile - Ebpf Agent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by (pod) (increase(originx_sr_signal_profile_count{node_name=~\"$node_name\", pod=~\"$pod\", is_hit=\"true\"}[$interval]))",
     "legendFormat": "{{pod}}_hit"
    },
    {
     "expr": "sum by (pod) (increase(originx_sr_signal_profile_count{node_name=~\"$node_name\", pod=~\"$pod\", is_hit=\"false\"}[$interval])>0)",
     "legendFormat": "{{pod}}_miss"
    }
   ]
  },
  {
   "title": "ApmTrace - Apo Receiver",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(originx_sr_adapter_apmtrace_count{is_hit=\"true\"}[$interval]))",
     "legendFormat": "Hit"
    },
    {
     "expr": "sum(increase(originx_sr_adapter_apmtrace_count{is_hit=\"false\"}[$interval]))",
     "legendFormat": "Miss"
    }
   ]
  },
  { "title": "Otel Collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Number of sampled spans",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by (sample) (increase(otelcol_processor_back_sampling_span_count{node_name=~\"$node_name\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Adaptive SampleRate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1/2^otelcol_processor_back_sampling_sample_value{node_name=~\"$node_name\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Number of successful and failed for sending spans",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum by (node_name) (increase(otelcol_exporter_sent_spans{node_name=~\"$node_name\"}[$interval]))",
     "legendFormat": "{{node_name}}-success"
    },
    {
     "expr": "sum by (node_name) (increase(otelcol_exporter_send_failed_spans{node_name=~\"$node_name\"}[$interval]))",
     "legendFormat": "{{node_name}}-failed"
    }
   ]
  }
 ]
}