{
 "title": "Service MiddleWare Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster_id",
    "label": "Cluster",
    "query": "SELECT DISTINCT scope_id AS __value, \nCASE \n  WHEN c.name != '' THEN c.name\n  ELSE scope_id\nEND AS __text\nFROM data_scope \nLEFT JOIN clusters c ON scope_id  = c.id\nWHERE type = 'cluster'"
   },
   {
    "name": "resolution",
    "label": "interval",
    "query": "1s, 15s, 30s, 1m, 3m, 5m , 10m, 30m"
   },
   {
    "name": "service",
    "label": "Service Name",
    "query": {
     "query": "label_values(kindling_db_duration_nanoseconds_sum{cluster_id=~\"$cluster_id\"},svc_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Avg Response Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by (svc_name, db_system, db_name, name, db_url) (increase(kindling_db_duration_nanoseconds_sum{svc_name=\"$service\", cluster_id=~\"$cluster_id\"}[$__rate_interval])) / sum by (svc_name, db_system, db_name, name, db_url) (increase(kindling_db_duration_nanoseconds_count{svc_name=\"$service\", cluster_id=~\"$cluster_id\"}[$__rate_interval])) ",
     "legendFormat": "{{db_url}}/{{db_name}}: {{name}}"
    }
   ]
  },
  {
   "title": "Request Error Rate(%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (svc_name, db_system, db_name, name, db_url) (increase(kindling_db_duration_nanoseconds_count{svc_name=\"$service\",is_error=\"true\", cluster_id=~\"$cluster_id\"}[$__rate_interval]))  / sum by (svc_name, db_system, db_name, name, db_url) (increase(kindling_db_duration_nanoseconds_count{svc_name=\"$service\", cluster_id=~\"$cluster_id\"}[$__rate_interval])) or (sum by (svc_name, db_system, db_name, name, db_url) (increase(kindling_db_duration_nanoseconds_count{svc_name=\"$service\", cluster_id=~\"$cluster_id\"}[$__rate_interval]))*0)",
     "legendFormat": "{{db_url}}/{{db_name}}: {{name}}"
    }
   ]
  },
  {
   "title": "Request Throughput Per Second (TPS)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (svc_name, db_system, db_name, name, db_url) (irate(kindling_db_duration_nanoseconds_count{svc_name=\"$service\", cluster_id=~\"$cluster_id\"}[$__rate_interval]))  ",
     "legendFormat": "{{db_url}}/{{db_name}}: {{name}}"
    }
   ]
  }
 ]
}