{
 "title": "Thread Polaris Metrics(VM)",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster_id",
    "label": "Cluster",
    "query": "SELECT DISTINCT scope_id AS __value, \nCASE \n  WHEN c.name != '' THEN c.name\n  ELSE scope_id\nEND AS __text\nFROM data_scope \nLEFT JOIN clusters c ON scope_id  = c.id\nWHERE type = 'cluster'"
   },
   {
    "name": "node",
    "label": "HostName",
    "query": {
     "query": "label_values(originx_thread_polaris_nanoseconds_count{type=\"cpu\", cluster_id=~\"$cluster_id\"},node_name)"
    }
   },
   {
    "name": "pid",
    "label": "PID",
    "query": {
     "query": "label_values(originx_thread_polaris_nanoseconds_count{type=\"cpu\", node_name=\"$node\",cluster_id=~\"$cluster_id\"},pid)"
    }
   },
   {
    "name": "tid",
    "label": "Thread",
    "query": {
     "query": "label_values(originx_thread_polaris_nanoseconds_count{pid=~\"$pid\", cluster_id=~\"$cluster_id\"},tid_key)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "15s,30s,1m,5m,10m,30m,1h,6h,12h,1d,7d"
   }
  ]
 },
 "panels": [
  {
   "title": "Agent Resources Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{container=\"ebpf-agent\", cluster_id=~\"$cluster_id\"}[2m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_rss{container=\"ebpf-agent\", cluster_id=~\"$cluster_id\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Application Resources Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{name=~\"$container_id.*\", cluster_id=~\"$cluster_id\"}[2m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_rss{name=~\"$container_id.*\", cluster_id=~\"$cluster_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Active Thread Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "count(increase(originx_thread_polaris_nanoseconds_count{pid=~\"$pid\", type=\"cpu\", cluster_id=~\"$cluster_id\"}[$interval]) > 0) or 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Thread Count by Type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "count(increase(originx_thread_polaris_nanoseconds_count{pid=~\"$pid\", type=\"futex\", cluster_id=~\"$cluster_id\"}[$interval]) > 0) or 0",
       "legendFormat": "Futex"
      },
      {
       "expr": "count(increase(originx_thread_polaris_nanoseconds_count{pid=~\"$pid\", type=\"net\", cluster_id=~\"$cluster_id\"}[$interval]) > 0) or 0",
       "legendFormat": "Net"
      },
      {
       "expr": "count(increase(originx_thread_polaris_nanoseconds_count{pid=~\"$pid\", type=\"epoll\", cluster_id=~\"$cluster_id\"}[$interval]) > 0) or 0",
       "legendFormat": "Epoll"
      },
      {
       "expr": "count(increase(originx_thread_polaris_nanoseconds_count{pid=~\"$pid\", type=\"file\", cluster_id=~\"$cluster_id\"}[$interval]) > 0) or 0",
       "legendFormat": "File"
      },
      {
       "expr": "count(increase(originx_thread_polaris_nanoseconds_count{pid=~\"$pid\", type=\"other\", cluster_id=~\"$cluster_id\"}[$interval]) > 0) or 0",
       "legendFormat": "Other"
      },
      {
       "expr": "count(increase(originx_thread_polaris_nanoseconds_count{pid=~\"$pid\", type=\"runq\", cluster_id=~\"$cluster_id\"}[$interval]) > 0) or 0",
       "legendFormat": "Runq"
      }
     ]
    }
   ]
  },
  {
   "title": "Polaris Histogram Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Time Histogram",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum by (le)(increase(prometheus_buckets(originx_thread_polaris_nanoseconds_bucket{pid=~\"$pid\", tid_key=~\"$tid\", type=\"cpu\", cluster_id=~\"$cluster_id\"})[$interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Futex Time Histogram",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "sum by (le)(increase(prometheus_buckets(originx_thread_polaris_nanoseconds_bucket{pid=~\"$pid\", tid_key=~\"$tid\", type=\"futex\", cluster_id=~\"$cluster_id\"})[$interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Net Time Histogram",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "sum by (le)(increase(prometheus_buckets(originx_thread_polaris_nanoseconds_bucket{pid=~\"$pid\", tid_key=~\"$tid\", type=\"net\", cluster_id=~\"$cluster_id\"})[$interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Epoll Time Histogram",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "sum by (le)(increase(prometheus_buckets(originx_thread_polaris_nanoseconds_bucket{pid=~\"$pid\", tid_key=~\"$tid\", type=\"epoll\", cluster_id=~\"$cluster_id\"})[$interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "File Time Histogram",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "sum by (le)(increase(prometheus_buckets(originx_thread_polaris_nanoseconds_bucket{pid=~\"$pid\", tid_key=~\"$tid\", type=\"file\", cluster_id=~\"$cluster_id\"})[$interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Other Time Histogram",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "sum by (le)(increase(prometheus_buckets(originx_thread_polaris_nanoseconds_bucket{pid=~\"$pid\", tid_key=~\"$tid\", type=\"other\", cluster_id=~\"$cluster_id\"})[$interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Runq Time Histogram",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "sum by (le)(increase(prometheus_buckets(originx_thread_polaris_nanoseconds_bucket{pid=~\"$pid\", tid_key=~\"$tid\", type=\"runq\", cluster_id=~\"$cluster_id\"})[$interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Polaris Call Count (All Threads)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "OnCPU Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_count{pid=~\"$pid\", tid_key=~\"$tid\", type=\"cpu\", cluster_id=~\"$cluster_id\"}[$interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Futex",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_count{pid=~\"$pid\", tid_key=~\"$tid\", type=\"futex\", cluster_id=~\"$cluster_id\"}[$interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Net",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_count{pid=~\"$pid\", tid_key=~\"$tid\", type=\"net\", cluster_id=~\"$cluster_id\"}[$interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Epoll",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_count{pid=~\"$pid\", tid_key=~\"$tid\", type=\"epoll\", cluster_id=~\"$cluster_id\"}[$interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "File",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_count{pid=~\"$pid\", tid_key=~\"$tid\", type=\"file\", cluster_id=~\"$cluster_id\"}[$interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Other",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_count{pid=~\"$pid\", tid_key=~\"$tid\", type=\"other\", cluster_id=~\"$cluster_id\"}[$interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Runq",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_count{pid=~\"$pid\", tid_key=~\"$tid\", type=\"runq\", cluster_id=~\"$cluster_id\"}[$interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Idle",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_count{pid=~\"$pid\", tid_key=~\"$tid\", type=\"idle\", cluster_id=~\"$cluster_id\"}[$interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Polaris Metrics (All Threads)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "On CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=~\"$tid\", type=\"cpu\", cluster_id=~\"$cluster_id\"}[$interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "On CPU P90",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(originx_thread_polaris_nanoseconds_bucket{pid=~\"$pid\", tid_key=~\"$tid\", type=\"cpu\", cluster_id=~\"$cluster_id\"}[$interval]))  by (container_id, tid, vmrange))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "File",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=~\"$tid\", type=\"file\", cluster_id=~\"$cluster_id\"}[$interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "File P90",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(originx_thread_polaris_nanoseconds_bucket{pid=~\"$pid\", tid_key=~\"$tid\", type=\"file\", cluster_id=~\"$cluster_id\"}[$interval]))  by (container_id, tid, vmrange))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Net",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=~\"$tid\", type=\"net\", cluster_id=~\"$cluster_id\"}[$interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Net P90",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(originx_thread_polaris_nanoseconds_bucket{pid=~\"$pid\", tid_key=~\"$tid\", type=\"net\", cluster_id=~\"$cluster_id\"}[$interval]))  by (container_id, tid, vmrange))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Epoll",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=~\"$tid\", type=\"epoll\", cluster_id=~\"$cluster_id\"}[$interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Epoll P90",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(originx_thread_polaris_nanoseconds_bucket{pid=~\"$pid\", tid_key=~\"$tid\", type=\"epoll\", cluster_id=~\"$cluster_id\"}[$interval]))  by (container_id, tid, vmrange))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Futex",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=~\"$tid\", type=\"futex\", cluster_id=~\"$cluster_id\"}[$interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Futex P90",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(originx_thread_polaris_nanoseconds_bucket{pid=~\"$pid\", tid_key=~\"$tid\", type=\"futex\", cluster_id=~\"$cluster_id\"}[$interval]))  by (container_id, tid, vmrange))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Other",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=~\"$tid\", type=\"other\", cluster_id=~\"$cluster_id\"}[$interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Other P90",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(originx_thread_polaris_nanoseconds_bucket{pid=~\"$pid\", tid_key=~\"$tid\", type=\"other\", cluster_id=~\"$cluster_id\"}[$interval]))  by (container_id, tid, vmrange))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Runqueue Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=~\"$tid\", type=\"runq\", cluster_id=~\"$cluster_id\"}[$interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Runq P90",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(originx_thread_polaris_nanoseconds_bucket{pid=~\"$pid\", tid_key=~\"$tid\", type=\"runq\", cluster_id=~\"$cluster_id\"}[$interval]))  by (container_id, tid, vmrange))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Polaris Metrics (Process Level)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time Stack",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "increase(sum without (tid_key) (originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", type=\"cpu\", cluster_id=~\"$cluster_id\"})[$interval])",
       "legendFormat": "OnCPU"
      },
      {
       "expr": "increase(sum without (tid_key) (originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", type=\"file\", cluster_id=~\"$cluster_id\"})[$interval])",
       "legendFormat": "File"
      },
      {
       "expr": "increase(sum without (tid_key) (originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", type=\"net\", cluster_id=~\"$cluster_id\"})[$interval])",
       "legendFormat": "Net"
      },
      {
       "expr": "increase(sum without (tid_key) (originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", type=\"epoll\", cluster_id=~\"$cluster_id\"})[$interval])",
       "legendFormat": "Epoll"
      },
      {
       "expr": "increase(sum without (tid_key) (originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", type=\"futex\", cluster_id=~\"$cluster_id\"})[$interval])",
       "legendFormat": "Futex"
      },
      {
       "expr": "increase(sum without (tid_key) (originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", type=\"idle\", cluster_id=~\"$cluster_id\"})[$interval])",
       "legendFormat": "Idle"
      },
      {
       "expr": "increase(sum without (tid_key) (originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", type=\"other\", cluster_id=~\"$cluster_id\"})[$interval])",
       "legendFormat": "Other"
      },
      {
       "expr": "increase(sum without (tid_key) (originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", type=\"runq\", cluster_id=~\"$cluster_id\"})[$interval])",
       "legendFormat": "Runqueue"
      }
     ]
    },
    {
     "title": "Time Lines",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "increase(sum without (tid_key) (originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", type=\"cpu\", cluster_id=~\"$cluster_id\"})[$interval])",
       "legendFormat": "OnCPU"
      },
      {
       "expr": "increase(sum without (tid_key) (originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", type=\"file\", cluster_id=~\"$cluster_id\"})[$interval])",
       "legendFormat": "File"
      },
      {
       "expr": "increase(sum without (tid_key) (originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", type=\"net\", cluster_id=~\"$cluster_id\"})[$interval])",
       "legendFormat": "Net"
      },
      {
       "expr": "increase(sum without (tid_key) (originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", type=\"epoll\", cluster_id=~\"$cluster_id\"})[$interval])",
       "legendFormat": "Epoll"
      },
      {
       "expr": "increase(sum without (tid_key) (originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", type=\"futex\", cluster_id=~\"$cluster_id\"})[$interval])",
       "legendFormat": "Futex"
      },
      {
       "expr": "increase(sum without (tid_key) (originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", type=\"idle\", cluster_id=~\"$cluster_id\"})[$interval])",
       "legendFormat": "Idle"
      },
      {
       "expr": "increase(sum without (tid_key) (originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", type=\"other\", cluster_id=~\"$cluster_id\"})[$interval])",
       "legendFormat": "Other"
      },
      {
       "expr": "increase(sum without (tid_key) (originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", type=\"runq\", cluster_id=~\"$cluster_id\"})[$interval])",
       "legendFormat": "Runqueue"
      }
     ]
    },
    {
     "title": "Time Pie Chart",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "increase(sum without (tid_key) (originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", type=\"cpu\", cluster_id=~\"$cluster_id\"})[$interval])",
       "legendFormat": "OnCPU"
      },
      {
       "expr": "increase(sum without (tid_key) (originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", type=\"file\", cluster_id=~\"$cluster_id\"})[$interval])",
       "legendFormat": "File"
      },
      {
       "expr": "increase(sum without (tid_key) (originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", type=\"net\", cluster_id=~\"$cluster_id\"})[$interval])",
       "legendFormat": "Net"
      },
      {
       "expr": "increase(sum without (tid_key) (originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", type=\"epoll\", cluster_id=~\"$cluster_id\"})[$interval])",
       "legendFormat": "Epoll"
      },
      {
       "expr": "increase(sum without (tid_key) (originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", type=\"futex\", cluster_id=~\"$cluster_id\"})[$interval])",
       "legendFormat": "Futex"
      },
      {
       "expr": "increase(sum without (tid_key) (originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", type=\"idle\", cluster_id=~\"$cluster_id\"})[$interval])",
       "legendFormat": "Idle"
      },
      {
       "expr": "increase(sum without (tid_key) (originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", type=\"other\", cluster_id=~\"$cluster_id\"})[$interval])",
       "legendFormat": "Other"
      },
      {
       "expr": "increase(sum without (tid_key) (originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", type=\"runq\", cluster_id=~\"$cluster_id\"})[$interval])",
       "legendFormat": "Runqueue"
      }
     ]
    }
   ]
  },
  {
   "title": "Polaris Metrics (Only when single thread is selected)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time Stack",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=\"$tid\", type=\"cpu\", cluster_id=~\"$cluster_id\"}[$interval])",
       "legendFormat": "OnCPU"
      },
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=\"$tid\", type=\"file\", cluster_id=~\"$cluster_id\"}[$interval])",
       "legendFormat": "File"
      },
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=\"$tid\", type=\"net\", cluster_id=~\"$cluster_id\"}[$interval])",
       "legendFormat": "Net"
      },
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=\"$tid\", type=\"epoll\", cluster_id=~\"$cluster_id\"}[$interval])",
       "legendFormat": "Epoll"
      },
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=\"$tid\", type=\"futex\", cluster_id=~\"$cluster_id\"}[$interval])",
       "legendFormat": "Futex"
      },
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=\"$tid\", type=\"idle\", cluster_id=~\"$cluster_id\"}[$interval])",
       "legendFormat": "Idle"
      },
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=\"$tid\", type=\"other\", cluster_id=~\"$cluster_id\"}[$interval])",
       "legendFormat": "Other"
      },
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=\"$tid\", type=\"runq\", cluster_id=~\"$cluster_id\"}[$interval])",
       "legendFormat": "Runqueue"
      }
     ]
    },
    {
     "title": "Time Lines",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=\"$tid\", type=\"cpu\", cluster_id=~\"$cluster_id\"}[$interval])",
       "legendFormat": "OnCPU"
      },
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=\"$tid\", type=\"file\", cluster_id=~\"$cluster_id\"}[$interval])",
       "legendFormat": "File"
      },
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=\"$tid\", type=\"net\", cluster_id=~\"$cluster_id\"}[$interval])",
       "legendFormat": "Net"
      },
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=\"$tid\", type=\"epoll\", cluster_id=~\"$cluster_id\"}[$interval])",
       "legendFormat": "Epoll"
      },
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=\"$tid\", type=\"futex\", cluster_id=~\"$cluster_id\"}[$interval])",
       "legendFormat": "Futex"
      },
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=\"$tid\", type=\"idle\", cluster_id=~\"$cluster_id\"}[$interval])",
       "legendFormat": "Idle"
      },
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=\"$tid\", type=\"other\", cluster_id=~\"$cluster_id\"}[$interval])",
       "legendFormat": "Other"
      },
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=\"$tid\", type=\"runq\", cluster_id=~\"$cluster_id\"}[$interval])",
       "legendFormat": "Runqueue"
      }
     ]
    },
    {
     "title": "Time Pie Chart",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=\"$tid\", type=\"cpu\", cluster_id=~\"$cluster_id\"}[$interval])",
       "legendFormat": "OnCPU"
      },
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=\"$tid\", type=\"file\", cluster_id=~\"$cluster_id\"}[$interval])",
       "legendFormat": "File"
      },
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=\"$tid\", type=\"net\", cluster_id=~\"$cluster_id\"}[$interval])",
       "legendFormat": "Net"
      },
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=\"$tid\", type=\"epoll\", cluster_id=~\"$cluster_id\"}[$interval])",
       "legendFormat": "Epoll"
      },
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=\"$tid\", type=\"futex\", cluster_id=~\"$cluster_id\"}[$interval])",
       "legendFormat": "Futex"
      },
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=\"$tid\", type=\"idle\", cluster_id=~\"$cluster_id\"}[$interval])",
       "legendFormat": "Idle"
      },
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=\"$tid\", type=\"other\", cluster_id=~\"$cluster_id\"}[$interval])",
       "legendFormat": "Other"
      },
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=\"$tid\", type=\"runq\", cluster_id=~\"$cluster_id\"}[$interval])",
       "legendFormat": "Runqueue"
      }
     ]
    }
   ]
  }
 ]
}