{
 "title": "Thread Polaris Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total,namespace)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{namespace=\"$namespace\"},pod)"
    }
   },
   {
    "name": "container_id",
    "label": "ContainerID",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{pod=\"$pod\", namespace=\"$namespace\"},name)"
    }
   },
   {
    "name": "tid",
    "label": "ThreadID",
    "query": {
     "query": "label_values(originx_thread_polaris_nanoseconds_count{container_id=\"$container_id\"},tid)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "15s,30s,1m,5m,10m,30m,1h,6h,12h,1d,7d"
   }
  ]
 },
 "panels": [
  {
   "title": "Agent Resources Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{container=\"ebpf-agent\"}[2m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_rss{container=\"ebpf-agent\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Application Resources Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{name=~\"$container_id.*\"}[2m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_rss{name=~\"$container_id.*\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Active Thread Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "count(increase(originx_thread_polaris_nanoseconds_count{container_id=~\"$container_id\", type=\"cpu\"}[$interval]) > 0) or 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Thread Count by Type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "count(increase(originx_thread_polaris_nanoseconds_count{container_id=~\"$container_id\", type=\"futex\"}[$interval]) > 0) or 0",
       "legendFormat": "Futex"
      },
      {
       "expr": "count(increase(originx_thread_polaris_nanoseconds_count{container_id=~\"$container_id\", type=\"net\"}[$interval]) > 0) or 0",
       "legendFormat": "Net"
      },
      {
       "expr": "count(increase(originx_thread_polaris_nanoseconds_count{container_id=~\"$container_id\", type=\"epoll\"}[$interval]) > 0) or 0",
       "legendFormat": "Epoll"
      },
      {
       "expr": "count(increase(originx_thread_polaris_nanoseconds_count{container_id=~\"$container_id\", type=\"file\"}[$interval]) > 0) or 0",
       "legendFormat": "File"
      },
      {
       "expr": "count(increase(originx_thread_polaris_nanoseconds_count{container_id=~\"$container_id\", type=\"other\"}[$interval]) > 0) or 0",
       "legendFormat": "Other"
      },
      {
       "expr": "count(increase(originx_thread_polaris_nanoseconds_count{container_id=~\"$container_id\", type=\"runq\"}[$interval]) > 0) or 0",
       "legendFormat": "Runq"
      }
     ]
    }
   ]
  },
  {
   "title": "Polaris Histogram Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Time Histogram",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum by (le)(increase(prometheus_buckets(originx_thread_polaris_nanoseconds_bucket{container_id=~\"$container_id\", tid=~\"$tid\", type=\"cpu\"})[$interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Futex Time Histogram",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "sum by (le)(increase(prometheus_buckets(originx_thread_polaris_nanoseconds_bucket{container_id=~\"$container_id\", tid=~\"$tid\", type=\"futex\"})[$interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Net Time Histogram",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "sum by (le)(increase(prometheus_buckets(originx_thread_polaris_nanoseconds_bucket{container_id=~\"$container_id\", tid=~\"$tid\", type=\"net\"})[$interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Epoll Time Histogram",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "sum by (le)(increase(prometheus_buckets(originx_thread_polaris_nanoseconds_bucket{container_id=~\"$container_id\", tid=~\"$tid\", type=\"epoll\"})[$interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "File Time Histogram",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "sum by (le)(increase(prometheus_buckets(originx_thread_polaris_nanoseconds_bucket{container_id=~\"$container_id\", tid=~\"$tid\", type=\"file\"})[$interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Other Time Histogram",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "sum by (le)(increase(prometheus_buckets(originx_thread_polaris_nanoseconds_bucket{container_id=~\"$container_id\", tid=~\"$tid\", type=\"other\"})[$interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Runq Time Histogram",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "sum by (le)(increase(prometheus_buckets(originx_thread_polaris_nanoseconds_bucket{container_id=~\"$container_id\", tid=~\"$tid\", type=\"runq\"})[$interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Polaris Call Count (All Threads)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "OnCPU Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_count{container_id=~\"$container_id\", tid=~\"$tid\", type=\"cpu\"}[$interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Futex",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_count{container_id=~\"$container_id\", tid=~\"$tid\", type=\"futex\"}[$interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Net",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_count{container_id=~\"$container_id\", tid=~\"$tid\", type=\"net\"}[$interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Epoll",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_count{container_id=~\"$container_id\", tid=~\"$tid\", type=\"epoll\"}[$interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "File",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_count{container_id=~\"$container_id\", tid=~\"$tid\", type=\"file\"}[$interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Other",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_count{container_id=~\"$container_id\", tid=~\"$tid\", type=\"other\"}[$interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Runq",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_count{container_id=~\"$container_id\", tid=~\"$tid\", type=\"runq\"}[$interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Idle",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_count{container_id=~\"$container_id\", tid=~\"$tid\", type=\"idle\"}[$interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Polaris Metrics (All Threads)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "On CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", tid=~\"$tid\", type=\"cpu\"}[$interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "On CPU P90",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum(rate(originx_thread_polaris_nanoseconds_bucket{container_id=~\"$container_id\", tid=~\"$tid\", type=\"cpu\"}[$interval]))  by (container_id, tid, vmrange))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "File",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", tid=~\"$tid\", type=\"file\"}[$interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "File P90",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum(rate(originx_thread_polaris_nanoseconds_bucket{container_id=~\"$container_id\", tid=~\"$tid\", type=\"file\"}[$interval]))  by (container_id, tid, vmrange))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Net",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", tid=~\"$tid\", type=\"net\"}[$interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Net P90",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum(rate(originx_thread_polaris_nanoseconds_bucket{container_id=~\"$container_id\", tid=~\"$tid\", type=\"net\"}[$interval]))  by (container_id, tid, vmrange))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Epoll",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", tid=~\"$tid\", type=\"epoll\"}[$interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Epoll P90",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum(rate(originx_thread_polaris_nanoseconds_bucket{container_id=~\"$container_id\", tid=~\"$tid\", type=\"epoll\"}[$interval]))  by (container_id, tid, vmrange))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Futex",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", tid=~\"$tid\", type=\"futex\"}[$interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Futex P90",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum(rate(originx_thread_polaris_nanoseconds_bucket{container_id=~\"$container_id\", tid=~\"$tid\", type=\"futex\"}[$interval]))  by (container_id, tid, vmrange))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Other",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", tid=~\"$tid\", type=\"other\"}[$interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Other P90",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum(rate(originx_thread_polaris_nanoseconds_bucket{container_id=~\"$container_id\", tid=~\"$tid\", type=\"other\"}[$interval]))  by (container_id, tid, vmrange))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Runqueue Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", tid=~\"$tid\", type=\"runq\"}[$interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Runq P90",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum(rate(originx_thread_polaris_nanoseconds_bucket{container_id=~\"$container_id\", tid=~\"$tid\", type=\"runq\"}[$interval]))  by (container_id, tid, vmrange))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Polaris Metrics (Process Level)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time Stack",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "increase(sum without (tid) (originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", type=\"cpu\"})[$interval])",
       "legendFormat": "OnCPU"
      },
      {
       "expr": "increase(sum without (tid) (originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", type=\"file\"})[$interval])",
       "legendFormat": "File"
      },
      {
       "expr": "increase(sum without (tid) (originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", type=\"net\"})[$interval])",
       "legendFormat": "Net"
      },
      {
       "expr": "increase(sum without (tid) (originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", type=\"epoll\"})[$interval])",
       "legendFormat": "Epoll"
      },
      {
       "expr": "increase(sum without (tid) (originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", type=\"futex\"})[$interval])",
       "legendFormat": "Futex"
      },
      {
       "expr": "increase(sum without (tid) (originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", type=\"idle\"})[$interval])",
       "legendFormat": "Idle"
      },
      {
       "expr": "increase(sum without (tid) (originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", type=\"other\"})[$interval])",
       "legendFormat": "Other"
      },
      {
       "expr": "increase(sum without (tid) (originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", type=\"runq\"})[$interval])",
       "legendFormat": "Runqueue"
      }
     ]
    },
    {
     "title": "Time Lines",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "increase(sum without (tid) (originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", type=\"cpu\"})[$interval])",
       "legendFormat": "OnCPU"
      },
      {
       "expr": "increase(sum without (tid) (originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", type=\"file\"})[$interval])",
       "legendFormat": "File"
      },
      {
       "expr": "increase(sum without (tid) (originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", type=\"net\"})[$interval])",
       "legendFormat": "Net"
      },
      {
       "expr": "increase(sum without (tid) (originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", type=\"epoll\"})[$interval])",
       "legendFormat": "Epoll"
      },
      {
       "expr": "increase(sum without (tid) (originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", type=\"futex\"})[$interval])",
       "legendFormat": "Futex"
      },
      {
       "expr": "increase(sum without (tid) (originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", type=\"idle\"})[$interval])",
       "legendFormat": "Idle"
      },
      {
       "expr": "increase(sum without (tid) (originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", type=\"other\"})[$interval])",
       "legendFormat": "Other"
      },
      {
       "expr": "increase(sum without (tid) (originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", type=\"runq\"})[$interval])",
       "legendFormat": "Runqueue"
      }
     ]
    },
    {
     "title": "Time Pie Chart",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "increase(sum without (tid) (originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", type=\"cpu\"})[$interval])",
       "legendFormat": "OnCPU"
      },
      {
       "expr": "increase(sum without (tid) (originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", type=\"file\"})[$interval])",
       "legendFormat": "File"
      },
      {
       "expr": "increase(sum without (tid) (originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", type=\"net\"})[$interval])",
       "legendFormat": "Net"
      },
      {
       "expr": "increase(sum without (tid) (originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", type=\"epoll\"})[$interval])",
       "legendFormat": "Epoll"
      },
      {
       "expr": "increase(sum without (tid) (originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", type=\"futex\"})[$interval])",
       "legendFormat": "Futex"
      },
      {
       "expr": "increase(sum without (tid) (originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", type=\"idle\"})[$interval])",
       "legendFormat": "Idle"
      },
      {
       "expr": "increase(sum without (tid) (originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", type=\"other\"})[$interval])",
       "legendFormat": "Other"
      },
      {
       "expr": "increase(sum without (tid) (originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", type=\"runq\"})[$interval])",
       "legendFormat": "Runqueue"
      }
     ]
    }
   ]
  },
  {
   "title": "Polaris Metrics (Only when single thread is selected)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time Stack",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", tid=\"$tid\", type=\"cpu\"}[$interval])",
       "legendFormat": "OnCPU"
      },
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", tid=\"$tid\", type=\"file\"}[$interval])",
       "legendFormat": "File"
      },
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", tid=\"$tid\", type=\"net\"}[$interval])",
       "legendFormat": "Net"
      },
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", tid=\"$tid\", type=\"epoll\"}[$interval])",
       "legendFormat": "Epoll"
      },
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", tid=\"$tid\", type=\"futex\"}[$interval])",
       "legendFormat": "Futex"
      },
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", tid=\"$tid\", type=\"idle\"}[$interval])",
       "legendFormat": "Idle"
      },
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", tid=\"$tid\", type=\"other\"}[$interval])",
       "legendFormat": "Other"
      },
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", tid=\"$tid\", type=\"runq\"}[$interval])",
       "legendFormat": "Runqueue"
      }
     ]
    },
    {
     "title": "Time Lines",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", tid=\"$tid\", type=\"cpu\"}[$interval])",
       "legendFormat": "OnCPU"
      },
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", tid=\"$tid\", type=\"file\"}[$interval])",
       "legendFormat": "File"
      },
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", tid=\"$tid\", type=\"net\"}[$interval])",
       "legendFormat": "Net"
      },
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", tid=\"$tid\", type=\"epoll\"}[$interval])",
       "legendFormat": "Epoll"
      },
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", tid=\"$tid\", type=\"futex\"}[$interval])",
       "legendFormat": "Futex"
      },
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", tid=\"$tid\", type=\"idle\"}[$interval])",
       "legendFormat": "Idle"
      },
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", tid=\"$tid\", type=\"other\"}[$interval])",
       "legendFormat": "Other"
      },
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", tid=\"$tid\", type=\"runq\"}[$interval])",
       "legendFormat": "Runqueue"
      }
     ]
    },
    {
     "title": "Time Pie Chart",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", tid=\"$tid\", type=\"cpu\"}[$interval])",
       "legendFormat": "OnCPU"
      },
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", tid=\"$tid\", type=\"file\"}[$interval])",
       "legendFormat": "File"
      },
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", tid=\"$tid\", type=\"net\"}[$interval])",
       "legendFormat": "Net"
      },
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", tid=\"$tid\", type=\"epoll\"}[$interval])",
       "legendFormat": "Epoll"
      },
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", tid=\"$tid\", type=\"futex\"}[$interval])",
       "legendFormat": "Futex"
      },
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", tid=\"$tid\", type=\"idle\"}[$interval])",
       "legendFormat": "Idle"
      },
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", tid=\"$tid\", type=\"other\"}[$interval])",
       "legendFormat": "Other"
      },
      {
       "expr": "increase(originx_thread_polaris_nanoseconds_sum{container_id=~\"$container_id\", tid=\"$tid\", type=\"runq\"}[$interval])",
       "legendFormat": "Runqueue"
      }
     ]
    }
   ]
  }
 ]
}