{
 "title": "Java探针监控",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node_name",
    "label": "探针所在节点",
    "query": "select labels['node_name'] as node_name\nfrom apo.originx_agent_event\ngroup by node_name\norder by node_name"
   },
   {
    "name": "start_time",
    "label": "探针启动时间",
    "query": "SELECT labels['agent_start_time'] as start_time FROM apo.originx_agent_event\nWHERE name='start_agent' and labels['node_name']='${node_name}' and labels['agent_start_time'] != ''\nGROUP BY start_time\nORDER BY start_time  desc"
   }
  ]
 },
 "panels": [
  { "title": "统计", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "容器Java应用统计",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(1) as not_monit_num FROM apo.originx_agent_event\r\nWHERE name='attach_java' and labels['node_name']='${node_name}' and labels['agent_start_time']='${start_time}'\r\nand labels['container_id'] != '' and status=false"
    },
    {
     "rawSql": "SELECT count(1) as monited_num FROM apo.originx_agent_event\r\nWHERE name='attach_java' and labels['node_name']='${node_name}' and labels['agent_start_time']='${start_time}'\r\nand labels['container_id'] != '' and status=true"
    }
   ]
  },
  {
   "title": "虚机Java应用统计",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(1) as not_monit_num FROM apo.originx_agent_event\r\nWHERE name='attach_java' and labels['node_name']='${node_name}' and labels['agent_start_time']='${start_time}'\r\nand labels['container_id'] = '' and status=false"
    },
    {
     "rawSql": "SELECT count(1) as monited_num FROM apo.originx_agent_event\r\nWHERE name='attach_java' and labels['node_name']='${node_name}' and labels['agent_start_time']='${start_time}'\r\nand labels['container_id'] = '' and status=true"
    }
   ]
  },
  { "title": "明细", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "容器应用列表",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, status, labels['pod_name'] as pod_name, labels['container_id'] as container_id, labels['host_name'] as host_name\r\nFROM apo.originx_agent_event\r\nWHERE name='attach_java' and labels['node_name']='${node_name}' and labels['agent_start_time']='${start_time}'\r\nand container_id !=''\r\nORDER BY status, timestamp desc\r\nLIMIT 1000"
    }
   ]
  },
  {
   "title": "虚机应用服务列表",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, status, pid, labels['command_line'] as cmd_line\r\nFROM apo.originx_agent_event\r\nWHERE name='attach_java' and labels['node_name']='${node_name}' and labels['agent_start_time']='${start_time}'\r\nand labels['container_id'] =''\r\nORDER BY timestamp desc\r\nLIMIT 1000"
    }
   ]
  }
 ]
}