{
 "title": "Originx 北极星指标 (容器层级)",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster_id",
    "label": "集群",
    "query": "SELECT DISTINCT scope_id AS __value, \nCASE \n  WHEN c.name != '' THEN c.name\n  ELSE scope_id\nEND AS __text\nFROM data_scope \nLEFT JOIN clusters c ON scope_id  = c.id\nWHERE type = 'cluster'"
   },
   {
    "name": "service_name",
    "label": "服务名",
    "query": {
     "query": "label_values(kindling_span_trace_duration_nanoseconds_count,svc_name)"
    }
   },
   {
    "name": "container_id",
    "label": "ContainerID",
    "query": {
     "query": "label_values(kindling_span_trace_duration_nanoseconds_count{svc_name=\"$service_name\", cluster_id=~\"$cluster_id\"},container_id)"
    }
   },
   {
    "name": "content_key",
    "label": "请求端点",
    "query": {
     "query": "label_values(kindling_span_trace_duration_nanoseconds_count{svc_name=~\"$service_name\", cluster_id=~\"$cluster_id\"},content_key)"
    }
   },
   {
    "name": "interval",
    "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "RED指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "请求次数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (content_key, svc_name) (increase(kindling_span_trace_duration_nanoseconds_count{svc_name=~\"$service_name\", content_key=~\"$content_key\", container_id=~\"$container_id\", cluster_id=~\"$cluster_id\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "请求成功率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (svc_name, content_key) (increase(kindling_span_trace_duration_nanoseconds_count{is_error=\"false\", svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\", cluster_id=~\"$cluster_id\"}[$interval]))/sum by (svc_name, content_key) (increase(kindling_span_trace_duration_nanoseconds_count{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\", cluster_id=~\"$cluster_id\"}[$interval])) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "平均响应时间",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (svc_name, content_key) (increase(kindling_span_trace_duration_nanoseconds_sum{svc_name=~\"$service_name\", content_key=~\"$content_key\", container_id=~\"$container_id\", cluster_id=~\"$cluster_id\"}[$interval]))/sum by (svc_name, content_key) (increase(kindling_span_trace_duration_nanoseconds_count{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\", cluster_id=~\"$cluster_id\"}[$interval]))/1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "响应时间分位数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_span_trace_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\", container_id=~\"$container_id\", cluster_id=~\"$cluster_id\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "P90: 服务名={{svc_name}}, 请求端点={{content_key}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kindling_span_trace_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\", cluster_id=~\"$cluster_id\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "P95: 服务名={{svc_name}}, 请求端点={{content_key}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kindling_span_trace_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\", cluster_id=~\"$cluster_id\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "P99: 服务名={{svc_name}}, 请求端点={{content_key}}"
    }
   ]
  },
  { "title": "北极星指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "北极星综合指标",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_span_trace_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\", cluster_id=~\"$cluster_id\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "P90 总延时"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_profiling_net_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\", cluster_id=~\"$cluster_id\"}[$interval])) by (svc_name, content_key, vmrange)) + histogram_quantile(0.9, sum(rate(kindling_profiling_epoll_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\", cluster_id=~\"$cluster_id\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "P90 等待网络耗时"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_profiling_file_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\", cluster_id=~\"$cluster_id\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "P90 等待文件耗时"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_profiling_futex_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\", cluster_id=~\"$cluster_id\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "P90 锁/GC耗时"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_profiling_cpu_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\", cluster_id=~\"$cluster_id\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "P90 onCPU执行耗时"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_profiling_runq_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\", cluster_id=~\"$cluster_id\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "P90 CPU调度耗时"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_profiling_other_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\", cluster_id=~\"$cluster_id\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "P90其他耗时"
    }
   ]
  },
  {
   "title": "快速判断是否是网络问题：将应用和下游应用同时看即可",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_profiling_net_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\", cluster_id=~\"$cluster_id\"}[$interval])) by (svc_name, content_key, vmrange)) + histogram_quantile(0.9, sum(rate(kindling_profiling_epoll_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\", cluster_id=~\"$cluster_id\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "{{svc_name}} 对外调用耗时"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_span_trace_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\", cluster_id=~\"$cluster_id\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "{{svc_name}} 延时"
    }
   ]
  },
  {
   "title": "快速判断容器规格是否需要提升",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_profiling_runq_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\", cluster_id=~\"$cluster_id\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "等待CPU调度P90耗时"
    },
    {
     "expr": "sum by (content_key, svc_name) (increase(kindling_span_trace_duration_nanoseconds_count{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\", cluster_id=~\"$cluster_id\"}[$interval]))",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "快速判断锁耗时是否影响了吞吐量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_profiling_futex_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\", cluster_id=~\"$cluster_id\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "等待锁/GC P90耗时"
    },
    {
     "expr": "sum by (content_key, svc_name) (increase(kindling_span_trace_duration_nanoseconds_count{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\", cluster_id=~\"$cluster_id\"}[$interval]))",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "每次请求中在CPU上执行的平均耗时",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by (content_key, svc_name) (increase(kindling_profiling_cpu_duration_nanoseconds_sum{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\", cluster_id=~\"$cluster_id\"}[$interval]))/sum by (content_key, svc_name) (increase(kindling_profiling_cpu_duration_nanoseconds_count{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\", cluster_id=~\"$cluster_id\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "每次请求中在CPU上执行的耗时90%分位数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_profiling_cpu_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\", cluster_id=~\"$cluster_id\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "每次请求中的网络平均耗时",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by (content_key, svc_name) (increase(kindling_profiling_net_duration_nanoseconds_sum{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\", cluster_id=~\"$cluster_id\"}[$interval]))/sum by (content_key, svc_name) (increase(kindling_profiling_net_duration_nanoseconds_count{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\", cluster_id=~\"$cluster_id\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "每次请求中的网络耗时90%分位数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_profiling_net_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\", cluster_id=~\"$cluster_id\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "每次请求中的epoll网络平均耗时",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by (content_key, svc_name) (increase(kindling_profiling_epoll_duration_nanoseconds_sum{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\", cluster_id=~\"$cluster_id\"}[$interval]))/sum by (content_key, svc_name) (increase(kindling_profiling_epoll_duration_nanoseconds_count{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\", cluster_id=~\"$cluster_id\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "每次请求中的epoll网络耗时90%分位数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_profiling_epoll_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\", cluster_id=~\"$cluster_id\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "每次请求中的锁等待或GC平均耗时",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by (content_key, svc_name) (increase(kindling_profiling_futex_duration_nanoseconds_sum{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\", cluster_id=~\"$cluster_id\"}[$interval]))/sum by (content_key, svc_name) (increase(kindling_profiling_futex_duration_nanoseconds_count{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\", cluster_id=~\"$cluster_id\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "每次请求中的锁等待或GC耗时90%分位数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_profiling_futex_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\", cluster_id=~\"$cluster_id\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "每次请求中的等待调度到CPU平均耗时",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by (content_key, svc_name) (increase(kindling_profiling_runq_duration_nanoseconds_sum{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\", cluster_id=~\"$cluster_id\"}[$interval]))/sum by (content_key, svc_name) (increase(kindling_profiling_runq_duration_nanoseconds_count{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\", cluster_id=~\"$cluster_id\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "每次请求中的等待调度到CPU耗时90%分位数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_profiling_runq_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\", cluster_id=~\"$cluster_id\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "每次请求中的文件读写平均耗时",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by (content_key, svc_name) (increase(kindling_profiling_file_duration_nanoseconds_sum{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\", cluster_id=~\"$cluster_id\"}[$interval]))/sum by (content_key, svc_name) (increase(kindling_profiling_file_duration_nanoseconds_count{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\", cluster_id=~\"$cluster_id\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "每次请求中的文件读写耗时90%分位数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(kindling_profiling_file_duration_nanoseconds_bucket{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\", cluster_id=~\"$cluster_id\"}[$interval])) by (svc_name, content_key, vmrange))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "每次请求中的等待其他资源平均耗时",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by (content_key, svc_name) (increase(kindling_profiling_other_duration_nanoseconds_sum{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\", cluster_id=~\"$cluster_id\"}[$interval]))/sum by (content_key, svc_name) (increase(kindling_profiling_other_duration_nanoseconds_count{svc_name=~\"$service_name\", content_key=~\"$content_key\",container_id=~\"$container_id\", cluster_id=~\"$cluster_id\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}