{
 "title": "Originx 数据自监控",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster_id",
    "label": "集群",
    "query": "SELECT DISTINCT scope_id AS __value, \nCASE \n  WHEN c.name != '' THEN c.name\n  ELSE scope_id\nEND AS __text\nFROM data_scope \nLEFT JOIN clusters c ON scope_id  = c.id\nWHERE type = 'cluster'"
   },
   {
    "name": "node_name",
    "label": "探针所在节点",
    "query": {
     "query": "label_values(originx_agent_ready,node_name)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kindling_span_trace_duration_nanoseconds_count{node_name=~\"$node_name\", cluster_id=~\"$cluster_id\"},pod)"
    }
   },
   {
    "name": "interval",
    "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "源头数据", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TxIn和TxOut事件数 - Ebpf Agent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (pod) (increase(originx_sr_tx_event_count{node_name=~\"$node_name\", pod=~\"$pod\", event_name=~\"txin\", cluster_id=~\"$cluster_id\"}[$interval]))",
     "legendFormat": "{{pod}}_txin"
    },
    {
     "expr": "sum by (pod) (increase(originx_sr_tx_event_count{node_name=~\"$node_name\", pod=~\"$pod\", event_name=~\"txout\", cluster_id=~\"$cluster_id\"}[$interval]))",
     "legendFormat": "{{pod}}_txout"
    }
   ]
  },
  {
   "title": "Java Lock事件数 - Ebpf Agent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (pod) (increase(originx_sr_tx_event_count{node_name=~\"$node_name\", pod=~\"$pod\", event_name=\"futex\", cluster_id=~\"$cluster_id\"}[$interval])>0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Trace关联数据", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "关联北极星Profile - Ebpf Agent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by (pod) (increase(originx_sr_signal_profile_count{node_name=~\"$node_name\", pod=~\"$pod\", is_hit=\"true\", cluster_id=~\"$cluster_id\"}[$interval]))",
     "legendFormat": "{{pod}}_匹配"
    },
    {
     "expr": "sum by (pod) (increase(originx_sr_signal_profile_count{node_name=~\"$node_name\", pod=~\"$pod\", is_hit=\"false\", cluster_id=~\"$cluster_id\"}[$interval])>0)",
     "legendFormat": "{{pod}}_未匹配"
    }
   ]
  },
  {
   "title": "对接ApmTrace - Apo Receiver",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(originx_sr_adapter_apmtrace_count{is_hit=\"true\", cluster_id=~\"$cluster_id\"}[$interval]))",
     "legendFormat": "匹配"
    },
    {
     "expr": "sum(increase(originx_sr_adapter_apmtrace_count{is_hit=\"false\", cluster_id=~\"$cluster_id\"}[$interval]))",
     "legendFormat": "未匹配"
    }
   ]
  },
  { "title": "Otel Collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "采样Span数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by (sample) (increase(otelcol_processor_back_sampling_span_count{node_name=~\"$node_name\", cluster_id=~\"$cluster_id\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "动态采样率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1/2^otelcol_processor_back_sampling_sample_value{node_name=~\"$node_name\", cluster_id=~\"$cluster_id\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "转发成功和失败Span数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum by (node_name) (increase(otelcol_exporter_sent_spans{node_name=~\"$node_name\", cluster_id=~\"$cluster_id\"}[$interval]))",
     "legendFormat": "{{node_name}}-success"
    },
    {
     "expr": "sum by (node_name) (increase(otelcol_exporter_send_failed_spans{node_name=~\"$node_name\", cluster_id=~\"$cluster_id\"}[$interval]))",
     "legendFormat": "{{node_name}}-failed"
    }
   ]
  }
 ]
}