{
 "title": "线程级北极星指标(VM)",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "HostName",
    "query": {
     "query": "label_values(originx_thread_polaris_nanoseconds_count{type=\"cpu\"},node_name)"
    }
   },
   {
    "name": "pid",
    "label": "PID",
    "query": {
     "query": "label_values(originx_thread_polaris_nanoseconds_count{type=\"cpu\", node_name=\"$node\"},pid)"
    }
   },
   {
    "name": "tid",
    "label": "Thread",
    "query": {
     "query": "label_values(originx_thread_polaris_nanoseconds_count{pid=~\"$pid\"},tid_key)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "15s,30s,1m,5m,10m,30m,1h,6h,12h,1d,7d"
   }
  ]
 },
 "panels": [
  {
   "title": "探针资源用量",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "探针CPU使用量",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{container=\"ebpf-agent\"}[2m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "探针内存使用量",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_rss{container=\"ebpf-agent\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "应用资源用量", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "进程CPU使用量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=~\"$container_id.*\"}[2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "进程内存使用量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_rss{name=~\"$container_id.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "活跃线程数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "count(increase(originx_thread_polaris_nanoseconds_count{pid=~\"$pid\", type=\"cpu\"}[$interval]) > 0) or 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "各类型线程数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "count(increase(originx_thread_polaris_nanoseconds_count{pid=~\"$pid\", type=\"futex\"}[$interval]) > 0) or 0",
     "legendFormat": "Futex"
    },
    {
     "expr": "count(increase(originx_thread_polaris_nanoseconds_count{pid=~\"$pid\", type=\"net\"}[$interval]) > 0) or 0",
     "legendFormat": "Net"
    },
    {
     "expr": "count(increase(originx_thread_polaris_nanoseconds_count{pid=~\"$pid\", type=\"epoll\"}[$interval]) > 0) or 0",
     "legendFormat": "Epoll"
    },
    {
     "expr": "count(increase(originx_thread_polaris_nanoseconds_count{pid=~\"$pid\", type=\"file\"}[$interval]) > 0) or 0",
     "legendFormat": "File"
    },
    {
     "expr": "count(increase(originx_thread_polaris_nanoseconds_count{pid=~\"$pid\", type=\"other\"}[$interval]) > 0) or 0",
     "legendFormat": "Other"
    },
    {
     "expr": "count(increase(originx_thread_polaris_nanoseconds_count{pid=~\"$pid\", type=\"runq\"}[$interval]) > 0) or 0",
     "legendFormat": "Runq"
    }
   ]
  },
  { "title": "耗时分布", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "CPU 耗时分布",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by (le)(increase(prometheus_buckets(originx_thread_polaris_nanoseconds_bucket{pid=~\"$pid\", tid_key=~\"$tid\", type=\"cpu\"})[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Futex 耗时分布",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum by (le)(increase(prometheus_buckets(originx_thread_polaris_nanoseconds_bucket{pid=~\"$pid\", tid_key=~\"$tid\", type=\"futex\"})[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Net 耗时分布",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum by (le)(increase(prometheus_buckets(originx_thread_polaris_nanoseconds_bucket{pid=~\"$pid\", tid_key=~\"$tid\", type=\"net\"})[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Epoll 耗时分布",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "sum by (le)(increase(prometheus_buckets(originx_thread_polaris_nanoseconds_bucket{pid=~\"$pid\", tid_key=~\"$tid\", type=\"epoll\"})[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "File 耗时分布",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum by (le)(increase(prometheus_buckets(originx_thread_polaris_nanoseconds_bucket{pid=~\"$pid\", tid_key=~\"$tid\", type=\"file\"})[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Other 耗时分布",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "sum by (le)(increase(prometheus_buckets(originx_thread_polaris_nanoseconds_bucket{pid=~\"$pid\", tid_key=~\"$tid\", type=\"other\"})[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Runq 耗时分布",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum by (le)(increase(prometheus_buckets(originx_thread_polaris_nanoseconds_bucket{pid=~\"$pid\", tid_key=~\"$tid\", type=\"runq\"})[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "北极星调用次数（全部线程）", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "OnCPU调用次数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(originx_thread_polaris_nanoseconds_count{pid=~\"$pid\", tid_key=~\"$tid\", type=\"cpu\"}[$interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Futex",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(originx_thread_polaris_nanoseconds_count{pid=~\"$pid\", tid_key=~\"$tid\", type=\"futex\"}[$interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Net调用次数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(originx_thread_polaris_nanoseconds_count{pid=~\"$pid\", tid_key=~\"$tid\", type=\"net\"}[$interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Epoll",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(originx_thread_polaris_nanoseconds_count{pid=~\"$pid\", tid_key=~\"$tid\", type=\"epoll\"}[$interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "File",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(originx_thread_polaris_nanoseconds_count{pid=~\"$pid\", tid_key=~\"$tid\", type=\"file\"}[$interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Other",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(originx_thread_polaris_nanoseconds_count{pid=~\"$pid\", tid_key=~\"$tid\", type=\"other\"}[$interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Runq",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(originx_thread_polaris_nanoseconds_count{pid=~\"$pid\", tid_key=~\"$tid\", type=\"runq\"}[$interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Idle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(originx_thread_polaris_nanoseconds_count{pid=~\"$pid\", tid_key=~\"$tid\", type=\"idle\"}[$interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "北极星指标（全部线程）", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "On CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=~\"$tid\", type=\"cpu\"}[$interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "On CPU P90",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(originx_thread_polaris_nanoseconds_bucket{pid=~\"$pid\", tid_key=~\"$tid\", type=\"cpu\"}[$interval]))  by (container_id, tid, vmrange))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "File",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=~\"$tid\", type=\"file\"}[$interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "File P90",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(originx_thread_polaris_nanoseconds_bucket{pid=~\"$pid\", tid_key=~\"$tid\", type=\"file\"}[$interval]))  by (container_id, tid, vmrange))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Net",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=~\"$tid\", type=\"net\"}[$interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Net P90",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(originx_thread_polaris_nanoseconds_bucket{pid=~\"$pid\", tid_key=~\"$tid\", type=\"net\"}[$interval]))  by (container_id, tid, vmrange))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Epoll",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=~\"$tid\", type=\"epoll\"}[$interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Epoll P90",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(originx_thread_polaris_nanoseconds_bucket{pid=~\"$pid\", tid_key=~\"$tid\", type=\"epoll\"}[$interval]))  by (container_id, tid, vmrange))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Futex",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=~\"$tid\", type=\"futex\"}[$interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Futex P90",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(originx_thread_polaris_nanoseconds_bucket{pid=~\"$pid\", tid_key=~\"$tid\", type=\"futex\"}[$interval]))  by (container_id, tid, vmrange))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Other",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=~\"$tid\", type=\"other\"}[$interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Other P90",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(originx_thread_polaris_nanoseconds_bucket{pid=~\"$pid\", tid_key=~\"$tid\", type=\"other\"}[$interval]))  by (container_id, tid, vmrange))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Runqueue Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=~\"$tid\", type=\"runq\"}[$interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Runq P90",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(originx_thread_polaris_nanoseconds_bucket{pid=~\"$pid\", tid_key=~\"$tid\", type=\"runq\"}[$interval]))  by (container_id, tid, vmrange))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "北极星指标（进程）",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 149 },
   "collapsed": true,
   "panels": [
    {
     "title": "各类型耗时叠图",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 157 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "increase(sum without (tid_key) (originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", type=\"cpu\"})[$interval])",
       "legendFormat": "OnCPU"
      },
      {
       "expr": "increase(sum without (tid_key) (originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", type=\"file\"})[$interval])",
       "legendFormat": "File"
      },
      {
       "expr": "increase(sum without (tid_key) (originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", type=\"net\"})[$interval])",
       "legendFormat": "Net"
      },
      {
       "expr": "increase(sum without (tid_key) (originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", type=\"epoll\"})[$interval])",
       "legendFormat": "Epoll"
      },
      {
       "expr": "increase(sum without (tid_key) (originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", type=\"futex\"})[$interval])",
       "legendFormat": "Futex"
      },
      {
       "expr": "increase(sum without (tid_key) (originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", type=\"idle\"})[$interval])",
       "legendFormat": "Idle"
      },
      {
       "expr": "increase(sum without (tid_key) (originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", type=\"other\"})[$interval])",
       "legendFormat": "Other"
      },
      {
       "expr": "increase(sum without (tid_key) (originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", type=\"runq\"})[$interval])",
       "legendFormat": "Runqueue"
      }
     ]
    },
    {
     "title": "各类型耗时折线图",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 157 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "increase(sum without (tid_key) (originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", type=\"cpu\"})[$interval])",
       "legendFormat": "OnCPU"
      },
      {
       "expr": "increase(sum without (tid_key) (originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", type=\"file\"})[$interval])",
       "legendFormat": "File"
      },
      {
       "expr": "increase(sum without (tid_key) (originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", type=\"net\"})[$interval])",
       "legendFormat": "Net"
      },
      {
       "expr": "increase(sum without (tid_key) (originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", type=\"epoll\"})[$interval])",
       "legendFormat": "Epoll"
      },
      {
       "expr": "increase(sum without (tid_key) (originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", type=\"futex\"})[$interval])",
       "legendFormat": "Futex"
      },
      {
       "expr": "increase(sum without (tid_key) (originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", type=\"idle\"})[$interval])",
       "legendFormat": "Idle"
      },
      {
       "expr": "increase(sum without (tid_key) (originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", type=\"other\"})[$interval])",
       "legendFormat": "Other"
      },
      {
       "expr": "increase(sum without (tid_key) (originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", type=\"runq\"})[$interval])",
       "legendFormat": "Runqueue"
      }
     ]
    },
    {
     "title": "各类型耗时占比",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 167 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "increase(sum without (tid_key) (originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", type=\"cpu\"})[$interval])",
       "legendFormat": "OnCPU"
      },
      {
       "expr": "increase(sum without (tid_key) (originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", type=\"file\"})[$interval])",
       "legendFormat": "File"
      },
      {
       "expr": "increase(sum without (tid_key) (originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", type=\"net\"})[$interval])",
       "legendFormat": "Net"
      },
      {
       "expr": "increase(sum without (tid_key) (originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", type=\"epoll\"})[$interval])",
       "legendFormat": "Epoll"
      },
      {
       "expr": "increase(sum without (tid_key) (originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", type=\"futex\"})[$interval])",
       "legendFormat": "Futex"
      },
      {
       "expr": "increase(sum without (tid_key) (originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", type=\"idle\"})[$interval])",
       "legendFormat": "Idle"
      },
      {
       "expr": "increase(sum without (tid_key) (originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", type=\"other\"})[$interval])",
       "legendFormat": "Other"
      },
      {
       "expr": "increase(sum without (tid_key) (originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", type=\"runq\"})[$interval])",
       "legendFormat": "Runqueue"
      }
     ]
    }
   ]
  },
  { "title": "北极星单线程（仅限筛选单线程）", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 150 } },
  {
   "title": "各类型耗时叠图",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=\"$tid\", type=\"cpu\"}[$interval])",
     "legendFormat": "OnCPU"
    },
    {
     "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=\"$tid\", type=\"file\"}[$interval])",
     "legendFormat": "File"
    },
    {
     "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=\"$tid\", type=\"net\"}[$interval])",
     "legendFormat": "Net"
    },
    {
     "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=\"$tid\", type=\"epoll\"}[$interval])",
     "legendFormat": "Epoll"
    },
    {
     "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=\"$tid\", type=\"futex\"}[$interval])",
     "legendFormat": "Futex"
    },
    {
     "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=\"$tid\", type=\"idle\"}[$interval])",
     "legendFormat": "Idle"
    },
    {
     "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=\"$tid\", type=\"other\"}[$interval])",
     "legendFormat": "Other"
    },
    {
     "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=\"$tid\", type=\"runq\"}[$interval])",
     "legendFormat": "Runqueue"
    }
   ]
  },
  {
   "title": "各类型耗时折线图",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=\"$tid\", type=\"cpu\"}[$interval])",
     "legendFormat": "OnCPU"
    },
    {
     "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=\"$tid\", type=\"file\"}[$interval])",
     "legendFormat": "File"
    },
    {
     "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=\"$tid\", type=\"net\"}[$interval])",
     "legendFormat": "Net"
    },
    {
     "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=\"$tid\", type=\"epoll\"}[$interval])",
     "legendFormat": "Epoll"
    },
    {
     "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=\"$tid\", type=\"futex\"}[$interval])",
     "legendFormat": "Futex"
    },
    {
     "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=\"$tid\", type=\"idle\"}[$interval])",
     "legendFormat": "Idle"
    },
    {
     "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=\"$tid\", type=\"other\"}[$interval])",
     "legendFormat": "Other"
    },
    {
     "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=\"$tid\", type=\"runq\"}[$interval])",
     "legendFormat": "Runqueue"
    }
   ]
  },
  {
   "title": "各类型总耗时占比",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 161 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=\"$tid\", type=\"cpu\"}[$interval])",
     "legendFormat": "OnCPU"
    },
    {
     "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=\"$tid\", type=\"file\"}[$interval])",
     "legendFormat": "File"
    },
    {
     "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=\"$tid\", type=\"net\"}[$interval])",
     "legendFormat": "Net"
    },
    {
     "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=\"$tid\", type=\"epoll\"}[$interval])",
     "legendFormat": "Epoll"
    },
    {
     "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=\"$tid\", type=\"futex\"}[$interval])",
     "legendFormat": "Futex"
    },
    {
     "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=\"$tid\", type=\"idle\"}[$interval])",
     "legendFormat": "Idle"
    },
    {
     "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=\"$tid\", type=\"other\"}[$interval])",
     "legendFormat": "Other"
    },
    {
     "expr": "increase(originx_thread_polaris_nanoseconds_sum{pid=~\"$pid\", tid_key=\"$tid\", type=\"runq\"}[$interval])",
     "legendFormat": "Runqueue"
    }
   ]
  }
 ]
}