name: tag release image

on:
  push:
    tags:
    - 'v*'

env:
  REGISTRY_HOST: registry.cn-hangzhou.aliyuncs.com
  CONTAINER_NAME: apo-grafana-init-dashboards

jobs:
  build-init-dashboards:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG_NAME: ${{ steps.build-image.outputs.IMAGE_TAG_NAME }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY_HOST }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Extract tag version
      id: vars
      run: echo "VERSION=${{ github.ref }}" >> $GITHUB_ENV

    - name: Build and push amd64 image
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: |
          linux/amd64
        push: true
        build-args: |
          APP_NAME=${{ env.CONTAINER_NAME }}
        tags: |
          ${{ env.REGISTRY_HOST }}/${{ secrets.REGISTRY_USERNAME }}/apo-grafana-init-dashboards:${{ env.VERSION }}
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ env.VERSION }}
        tag_name: ${{ env.VERSION }}
